const fs=require('fs');
const path=require('path');
const vscode=require('vscode');
const clone=value=>JSON.parse(JSON.stringify(value));
function merge(base,update){const result=clone(base);for(const [key,value]of Object.entries(update)){if(['__proto__','constructor','prototype'].includes(key))throw new Error('Invalid configuration key.');result[key]=value&&typeof value==='object'&&!Array.isArray(value)&&result[key]&&typeof result[key]==='object'&&!Array.isArray(result[key])?merge(result[key],value):clone(value);}return result;}
function unpack(value){value=value.params||value.probability_model_params||value;if(!value||typeof value!=='object'||Array.isArray(value))throw new Error('Parameters must be a JSON object.');if(value.cleavage_pattern_set||value.fragment_ion_adduct_rule_set)return {fragmenter_params:{fragment_ion_tree_builder:value}};return value.fragment_ion_tree_builder?{fragmenter_params:value}:value;}
function defaults(root){return JSON.parse(fs.readFileSync(path.join(root,'clefts/presets/spectrum_generator_params/source_anchored_pos_model_config.json'),'utf8'));}
function attach(panel,context,projectRoot){panel.webview.onDidReceiveMessage(async (/** @type {import('./messages').ParameterRequest} */ message)=>{if(!['parameters/load','parameters/pick','parameters/import'].includes(message?.type))return;if(!['data','training'].includes(message.target))return;try{let file=message.path;if(message.type==='parameters/pick'){const selected=await vscode.window.showOpenDialog({canSelectMany:false,canSelectFiles:true,canSelectFolders:false,filters:{'Parameter JSON':['json']}});if(!selected?.[0])return;file=selected[0].fsPath;}if(message.type==='parameters/import'){if(typeof message.json!=='string'||message.json.length>2000000)throw new Error('Parameter file is too large or invalid.');const modelConfig=merge(defaults(projectRoot(context)),unpack(JSON.parse(message.json)));panel.webview.postMessage({type:'parameters/loaded',target:message.target,path:message.name||'Imported JSON',modelConfig});return;}if(typeof file!=='string'||!file.trim())throw new Error('Select a parameter JSON file.');file=path.resolve(projectRoot(context),file);const text=await fs.promises.readFile(file,'utf8');if(text.length>2000000)throw new Error('Parameter file is too large.');const modelConfig=merge(defaults(projectRoot(context)),unpack(JSON.parse(text)));panel.webview.postMessage({type:'parameters/loaded',target:message.target,path:file,modelConfig});}catch(error){panel.webview.postMessage({type:'parameters/error',target:message.target,error:error.message});}});}
module.exports={merge,unpack,defaults,attach};
