/* RDKit direct-reaction preview within the Pattern Set workbench. */
function installReactionPreview(){
  const el=id=>document.getElementById(id),app=el('cleavageApp'),svgNS='http://www.w3.org/2000/svg';
  const style=document.createElement('style');style.textContent=`
  .rp-preview{scroll-margin-top:80px;background:#0b1728;border:1px solid #25465d;border-radius:10px;padding:16px;margin:18px 0;color:#dbeafe}.rp-preview h3{font-size:15px;margin:0 0 8px;color:#a4dfff}.rp-inputs{display:grid;grid-template-columns:145px 240px minmax(180px,1fr) auto;gap:12px;align-items:end;margin:16px 0}.rp-inputs label{margin:0}.rp-inputs button{min-height:36px}.rp-grid{display:grid;grid-template-columns:minmax(170px,.65fr) minmax(300px,1.65fr) minmax(260px,1fr);gap:14px}.rp-panel{background:#0c1625;border:1px solid #23435d;border-radius:8px;padding:14px;min-width:0}.rp-drawing{background:var(--vscode-editor-background,#1e1e1e);border:1px solid #294a65;border-radius:8px;overflow:hidden}.rp-drawing svg{display:block;width:100%;height:auto}.rp-reactant{min-height:320px}.rp-preview .muted{font-size:12px;color:#91afc5;margin:6px 0 12px}.rp-patterns{display:grid;gap:7px}.rp-patterns button,.rp-sites button,.rp-overlap button{text-align:left;white-space:normal;padding:9px 10px}.rp-preview button.active{background:#0d3b57;border-color:#38bdf8;color:#e2f5ff}.rp-patterns button{display:block;width:100%}.rp-selected-action{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:7px;align-items:center;padding:7px 0;border-bottom:1px solid #23435d;font-size:12px}.rp-selected-action button{width:auto;padding:5px 7px}.rp-field-label{display:block;font-size:10px;color:#91afc5;margin-top:10px}.rp-patterns small{display:block;color:#8cbeda;margin-top:4px}.rp-sites,.rp-overlap{display:flex;gap:7px;flex-wrap:wrap;margin-top:12px}.rp-sites button{border-left:3px solid var(--site-color)}.rp-details{margin-top:18px}.rp-field{display:flex;align-items:center;gap:6px;margin-top:8px}.rp-field input{font-family:monospace;font-size:11px;min-width:0;flex:1}.rp-field button{padding:6px;min-width:32px}.rp-products{display:grid;gap:12px}.rp-product{padding:12px;border:1px solid #2a4a63;border-radius:8px;background:#0d1d2e}.rp-product h4{margin:0 0 6px}.rp-molecules{display:grid;grid-template-columns:repeat(auto-fit,minmax(150px,1fr));gap:8px;margin:12px 0}.rp-formula{font-size:13px;font-weight:600;margin:7px 0 2px}.rp-mass{color:#8ea9bf;font-size:11px}.rp-empty{padding:20px 4px;color:#91afc5}.rp-hit{cursor:pointer}.rp-hit:hover{stroke:#fff!important;stroke-opacity:.5!important}.rp-error{color:#ff9292;font-size:12px;white-space:pre-wrap}.rp-status{font-size:12px;color:#8cbeda;margin:8px 0}.rp-grid[hidden]{display:none}@media(max-width:1100px){.rp-grid{grid-template-columns:190px minmax(300px,1fr)}.rp-product-panel{grid-column:1/-1}.rp-products{grid-template-columns:repeat(auto-fit,minmax(280px,1fr))}.rp-inputs{grid-template-columns:130px minmax(160px,1fr)}.rp-inputs .rp-smiles{grid-column:1/-1}}@media(max-width:650px){.rp-grid{grid-template-columns:1fr}.rp-product-panel{grid-column:auto}.rp-inputs{grid-template-columns:1fr}.rp-inputs .rp-smiles{grid-column:auto}}
  .rp-reactions{display:flex;gap:7px;flex-wrap:wrap;margin-top:12px}.rp-reactions button{text-align:left;white-space:normal;padding:9px 10px}
  `;document.head.append(style);
  const root=document.createElement('section');root.id='cleavageReactionPreview';root.className='rp-preview';root.hidden=true;
  root.innerHTML='<div class="section-title"><div><h2>Cleavage Pattern Reaction Preview</h2><p class="muted">Inspect direct reactions, enumerate simultaneous action sets, or build one interactively.</p></div><button type="button" id="closeReactionPreview" aria-label="Close reaction preview">×</button></div><div class="rp-inputs"><label>Mode<select id="reactionPreviewMode"><option value="direct">Direct preview</option><option value="stepwise">Stepwise actions</option><option value="exhaustive">Exhaustive candidates</option></select></label><label>Test target<select id="reactionPreviewScope"><option value="set">Pattern Set</option><option value="pattern">Pattern</option></select></label><label>Cleavage Pattern / Set<select id="reactionPreviewTarget"></select></label><label class="rp-smiles">Input SMILES<input id="reactionPreviewSmiles" placeholder="CCOCCO" spellcheck="false"></label><label class="rp-max-actions" hidden>Max actions<input id="reactionPreviewMaxActions" type="number" min="1" step="1" value="2"></label><button type="button" id="runReactionPreview" class="primary">Run Reaction Preview</button></div><p id="reactionPreviewError" class="rp-error" role="alert"></p><p id="reactionPreviewStatus" class="rp-status" role="status"></p><div class="rp-grid" hidden><aside class="rp-panel"><h3>Patterns</h3><div class="rp-patterns"></div><div class="rp-details"></div></aside><div class="rp-panel"><h3>Reactant</h3><p class="muted">Choose a reaction center, then a matching reactant and product.</p><div class="rp-drawing rp-reactant" id="reactionPreviewReactant"></div><div class="rp-overlap"></div><h3 style="margin-top:16px">Matched Reactions</h3><div class="rp-reactions"></div><h3 style="margin-top:16px">Matched Reactants</h3><div class="rp-sites"></div></div><div class="rp-panel rp-product-panel"><h3 id="reactionPreviewProductsTitle">Products</h3><p class="muted" id="reactionPreviewProductsHint">Direct products for the selected match</p><div class="rp-products"></div></div></div>';
  el('visualBuilder').before(root);
  const setButton=document.createElement('button');setButton.type='button';setButton.id='previewCleavageSet';setButton.textContent='Reaction Preview';el('saveCleavage').before(setButton);
  let results=null,filter=-1,selected=null,requestRevision=0,sourceIndices=[],definitionSnapshot='',previewSmiles='',previewDefinitions=[],explore=null,focusedAction=null,focusedSiteKey=null,focusedReactionKey=null,selectedActionIds=[];
  const colors=['#38bdf8','#a78bfa','#34d399','#fbbf24','#fb7185','#67e8f9'];
  const escape=value=>htmlEscape(String(value??''));
  function syncTargets(){const target=el('reactionPreviewTarget'),previous=target.value,patterns=cleavageModel.cleavage_pattern_set.patterns;if(el('reactionPreviewScope').value==='set')target.innerHTML='<option value="set">'+escape(cleavageModel.cleavage_pattern_set.name||'Current Pattern Set')+' ('+patterns.length+' patterns)</option>';else target.innerHTML=patterns.map((p,i)=>'<option value="'+i+'">'+escape(p.name||'Pattern '+(i+1))+'</option>').join('');if([...target.options].some(o=>o.value===previous))target.value=previous;}
  function clearResults(message=''){++requestRevision;results=null;explore=null;focusedAction=null;focusedSiteKey=null;focusedReactionKey=null;selectedActionIds=[];selected=null;root.querySelector('.rp-grid').hidden=true;el('reactionPreviewError').textContent='';el('reactionPreviewStatus').textContent=message;}
  function setMode(mode){el('reactionPreviewMode').value=mode;root.querySelector('.rp-max-actions').hidden=mode==='direct';el('runReactionPreview').textContent=mode==='direct'?'Run Reaction Preview':mode==='stepwise'?'Find Actions':'Generate Candidates';clearResults();}
  function editorHome(){el('visualBuilder').before(root);}
  function open(index){editorHome();root.hidden=false;setMode('direct');el('reactionPreviewScope').value=index===undefined?'set':'pattern';syncTargets();if(index!==undefined)el('reactionPreviewTarget').value=String(index);el('reactionPreviewSmiles').focus({preventScroll:true});root.scrollIntoView?.({block:'start'});}
  setButton.onclick=()=>open();el('closeReactionPreview').onclick=()=>{clearResults();root.hidden=true;};
  el('reactionPreviewMode').onchange=()=>setMode(el('reactionPreviewMode').value);el('reactionPreviewScope').onchange=()=>{syncTargets();clearResults();};el('reactionPreviewTarget').onchange=()=>clearResults();el('reactionPreviewSmiles').oninput=()=>clearResults();el('reactionPreviewMaxActions').oninput=()=>clearResults();
  window.addEventListener('cleavageViewer/open',()=>{el('cleavageViewerMount')?.append(root);root.hidden=false;setMode('stepwise');syncTargets();el('reactionPreviewSmiles').focus({preventScroll:true});});
  const baseRender=renderCleavage;renderCleavage=()=>{baseRender();el('cleavagePatterns').querySelectorAll('.pattern-card').forEach((card,i)=>{const button=document.createElement('button');button.type='button';button.dataset.previewPattern=i;button.textContent='Reaction Preview';card.querySelector('.actions').prepend(button);});syncTargets();if(definitionSnapshot&&definitionSnapshot!==JSON.stringify(cleavageModel.cleavage_pattern_set)){clearResults('Patterns changed. Run the preview again.');definitionSnapshot='';}};
  el('cleavagePatterns').addEventListener('click',event=>{const button=event.target.closest('[data-preview-pattern]');if(button)open(Number(button.dataset.previewPattern));});
  el('cleavageSetName').addEventListener('input',()=>{syncTargets();clearResults('Patterns changed. Run the preview again.');});
  app.addEventListener('input',event=>{if(event.target.dataset.pattern!==undefined)clearResults('Patterns changed. Run the preview again.');});
  function allSites(){return results?results.patterns.flatMap((pattern,pi)=>pattern.matches.map((match,mi)=>({pattern,pi,match,mi,color:colors[(pi+mi)%colors.length]}))):[];}
  function visibleSites(){return allSites().filter(site=>filter<0||site.pi===filter);}
  function field(label,value){return '<div class="rp-field-block"><span class="rp-field-label">'+escape(label)+'</span><div class="rp-field"><input readonly aria-label="'+escape(label)+'" value="'+escape(value)+'"><button type="button" aria-label="Copy '+escape(label)+'" title="Copy '+escape(label)+'" data-rp-copy>⧉</button></div></div>';}
  root.addEventListener('click',event=>{const button=event.target.closest('[data-rp-copy]');if(button)vscode.postMessage({type:'copyCleavageText',text:button.previousElementSibling.value});});
  async function choose(site){
    if(site.group){focusedAction=null;focusedSiteKey=focusedSiteKey===site.group.key?null:site.group.key;renderExplore();return;}
    selected=site.match.id;const match=site.match,revision=requestRevision,currentResults=results;
    if(match.loaded||match.loading){renderResults();return;}
    match.loading=true;renderResults();
    try{const response=await chemistry('reactionPreviewProducts',{smiles:previewSmiles,pattern:previewDefinitions[site.pi],atoms:match.atoms,bonds:match.bonds});if(revision!==requestRevision||currentResults!==results)return;match.products=response.products;match.errors=response.errors;match.loaded=true;if(response.truncated)match.errors.push('Preview limit reached; some results are omitted.');}
    catch(error){if(revision===requestRevision&&currentResults===results){match.errors=[error.message];match.loaded=true;}}
    finally{match.loading=false;if(revision===requestRevision&&currentResults===results&&selected===match.id)renderResults();}
  }
  function siteButton(site){const button=document.createElement('button');button.type='button';button.dataset.previewMatch=site.match.id;button.style.setProperty('--site-color',site.color);const active=site.group?site.group.key===focusedSiteKey:site.match.id===selected;button.classList.toggle('active',active);button.setAttribute('aria-pressed',String(active));button.textContent=site.group?site.group.patternName+' · atoms '+site.group.sourceAtomMaps.join(','):(filter<0?site.pattern.name+' · ':'')+'Match '+(site.mi+1)+' · '+(site.match.loaded?site.match.products.length+' product sets':site.pattern.productCount+' product definitions');button.title=site.group?'Atoms in source_atom_maps order: '+site.group.sourceAtomMaps.join(','):'Atoms '+site.match.atoms.map(i=>i+1).join(', ');button.onclick=()=>choose(site);return button;}
  function renderResults(){if(!results)return;const sites=visibleSites(),active=allSites().find(site=>site.match.id===selected),patterns=root.querySelector('.rp-patterns');patterns.replaceChildren();
    const addPattern=(label,count,index)=>{const button=document.createElement('button');button.type='button';button.classList.toggle('active',index===filter);button.setAttribute('aria-pressed',String(index===filter));button.innerHTML=escape(label)+'<small>'+count+' matches</small>';button.onclick=()=>{filter=index;selected=null;renderResults();};patterns.append(button);};
    if(results.patterns.length>1)addPattern('All patterns',allSites().length,-1);results.patterns.forEach((p,i)=>addPattern(p.name,p.matches.length,i));
    const detail=filter>=0?results.patterns[filter]:active?.pattern;root.querySelector('.rp-details').innerHTML=detail?'<h3>'+escape(detail.name)+'</h3><p class="muted">'+detail.matches.length+' matches · '+detail.productCount+' product definitions</p>'+field('Reactant SMARTS',detail.reactantSmarts)+'<p class="rp-error">'+escape(detail.errors.join('\n'))+'</p><button type="button" data-rp-edit>Edit selected pattern</button>':'<p class="muted">Select a pattern or matched site.</p>'+results.patterns.flatMap(p=>p.errors.map(error=>'<p class="rp-error">'+escape(p.name+': '+error)+'</p>')).join('');
    const edit=root.querySelector('[data-rp-edit]');if(edit)edit.onclick=()=>{root.hidden=true;editVisualPattern(sourceIndices[results.patterns.indexOf(detail)]);};
    renderDrawing(sites);const list=root.querySelector('.rp-sites');list.replaceChildren();sites.forEach(site=>list.append(siteButton(site)));if(!sites.length)list.innerHTML='<p class="rp-empty">No matching reactant sites.</p>';root.querySelector('.rp-overlap').replaceChildren();
    const products=root.querySelector('.rp-products');products.replaceChildren();el('reactionPreviewProductsTitle').textContent=active?'Products for Match '+(active.mi+1):'Products';
    if(!active){products.innerHTML='<p class="rp-empty">Click a highlighted site to display its products.</p>';return;}
    if(active.match.loading){products.innerHTML='<p class="rp-empty" role="status">Generating products for the selected site…</p>';return;}
    products.innerHTML='<p class="muted">'+escape(active.pattern.name)+' · '+active.match.products.length+' product sets</p>'+active.match.errors.map(e=>'<p class="rp-error">'+escape(e)+'</p>').join('');
    if(!active.match.products.length)products.insertAdjacentHTML('beforeend','<p class="rp-empty">No valid products for this match.</p>');
    active.match.products.forEach((product,i)=>{const card=document.createElement('article');card.className='rp-product';card.innerHTML='<h4>'+escape(product.name)+' · '+(i+1)+'</h4><p class="muted">'+product.molecules.length+' molecules</p><div class="rp-molecules">'+product.molecules.map(m=>'<div><div class="rp-drawing">'+m.drawing.svg+'</div><p class="rp-formula">'+escape(m.formula)+'</p><p class="rp-mass">Exact mass '+Number(m.exactMass).toFixed(4)+' Da</p>'+field('Molecule SMILES',m.smiles)+'</div>').join('')+'</div>'+field('Product SMILES',product.smiles)+field('Product SMARTS',product.smarts)+field('Reaction SMIRKS',product.smirks);products.append(card);});
  }
  function renderDrawing(sites){const container=el('reactionPreviewReactant');container.innerHTML=results.drawing.svg;const svg=container.querySelector('svg');svg.setAttribute('viewBox','0 0 760 500');svg.setAttribute('role','img');svg.setAttribute('aria-label','Reactant with clickable matched sites');const overlay=document.createElementNS(svgNS,'g');overlay.setAttribute('aria-hidden','true');
    function shape(tag,attributes,parent=overlay){const node=document.createElementNS(svgNS,tag);Object.entries(attributes).forEach(([key,value])=>node.setAttribute(key,String(value)));parent.append(node);return node;}
    const positions=results.drawing.positions,bonds=results.drawing.bonds;
    // Draw broad translucent markers without replacing RDKit's atom or bond paths.
    const isChosen=site=>site.reaction?site.reaction.key===focusedReactionKey:site.group?site.group.key===focusedSiteKey:site.match.id===selected;
    sites.slice().sort((a,b)=>Number(isChosen(a))-Number(isChosen(b))).forEach(site=>{const chosen=isChosen(site);site.match.bonds.forEach(id=>{const bond=bonds.find(b=>b.index===id);if(!bond)return;const a=positions[bond.begin],b=positions[bond.end];shape('line',{x1:a.x,y1:a.y,x2:b.x,y2:b.y,stroke:site.color,'stroke-width':chosen?13:9,'stroke-opacity':chosen?.5:.24,'stroke-linecap':'round','pointer-events':'none'});});site.match.atoms.forEach(id=>{const p=positions[id];shape('circle',{cx:p.x,cy:p.y,r:chosen?13:10,fill:site.color,'fill-opacity':.08,stroke:site.color,'stroke-width':chosen?2.5:1.5,'stroke-opacity':chosen?1:.55,'pointer-events':'none'});});});
    const hit=(node,candidates)=>{node.classList.add('rp-hit');node.onclick=async()=>{if(explore){const reaction=candidates[0].reaction;focusedReactionKey=reaction.key;focusedSiteKey=null;focusedAction=null;renderExplore();return;}const next=candidates[(candidates.findIndex(site=>site.match.id===selected)+1)%candidates.length];await choose(next);if(selected===next.match.id&&candidates.length>1){const chooser=root.querySelector('.rp-overlap');chooser.innerHTML='<p class="muted">Overlapping matches: choose a site</p>';candidates.forEach(site=>chooser.append(siteButton(site)));}};};
    [...new Set(sites.flatMap(site=>site.match.bonds))].forEach(id=>{const bond=bonds.find(b=>b.index===id),a=positions[bond.begin],b=positions[bond.end];hit(shape('line',{x1:a.x,y1:a.y,x2:b.x,y2:b.y,stroke:'transparent','stroke-width':22,'pointer-events':'stroke','data-preview-bond':id}),sites.filter(site=>site.match.bonds.includes(id)));});
    [...new Set(sites.flatMap(site=>site.match.atoms))].forEach(id=>{const p=positions[id];hit(shape('circle',{cx:p.x,cy:p.y,r:18,fill:'transparent',stroke:'transparent','pointer-events':'all','data-preview-atom':id}),sites.filter(site=>site.match.atoms.includes(id)));});svg.append(overlay);
  }
  function moleculeCard(molecule,title,extra=''){return '<article class="rp-product"><h4>'+escape(title)+'</h4>'+extra+'<div class="rp-molecules"><div><div class="rp-drawing">'+molecule.drawing.svg+'</div><p class="rp-formula">'+escape(molecule.formula)+'</p><p class="rp-mass">Exact mass '+Number(molecule.exactMass).toFixed(4)+' Da</p>'+field('Molecule SMILES',molecule.smiles)+'</div></div></article>';}
  function actionSiteKey(action){return action.patternIndex+':'+action.sourceAtomMaps.join(',');}
  function actionReactionKey(action){const bonds=action.reactionBondMaps.length?action.reactionBondMaps:action.changedBondMaps;return bonds.map(edge=>edge.join('-')).join('+');}
  function reactionGroups(){if(!explore)return[];const groups=new Map();for(const id of explore.availableActionIds){const action=explore.actions[id],key=actionReactionKey(action);if(!groups.has(key))groups.set(key,{key,bondMaps:action.reactionBondMaps.length?action.reactionBondMaps:action.changedBondMaps,bonds:action.reactionBonds.length?action.reactionBonds:action.bonds,actions:[]});groups.get(key).actions.push(action);}return[...groups.values()];}
  function exploreGroups(){if(!explore)return[];const included=new Set(explore.availableActionIds);if(focusedSiteKey)for(const id of explore.selectedActionIds)if(actionSiteKey(explore.actions[id])===focusedSiteKey)included.add(id);const groups=new Map();for(const id of included){const action=explore.actions[id],key=actionSiteKey(action);if(!groups.has(key))groups.set(key,{key,patternIndex:action.patternIndex,patternName:action.patternName,sourceAtomMaps:action.sourceAtomMaps,atoms:action.atoms,bonds:action.bonds,actions:[]});groups.get(key).actions.push(action);}return[...groups.values()];}
  function exploreSites(){if(!focusedReactionKey)return[];const available=new Set(explore.availableActionIds),groups=exploreGroups().filter(group=>group.actions.some(action=>available.has(action.id)&&actionReactionKey(action)===focusedReactionKey));return groups.map((group,i)=>({group,pattern:{name:group.patternName},pi:group.patternIndex,mi:i,match:{id:'site:'+group.key,atoms:group.atoms,bonds:group.bonds},color:colors[group.patternIndex%colors.length]}));}
  function reactionSites(){return reactionGroups().map((reaction,i)=>({reaction,match:{id:'reaction:'+reaction.key,atoms:[],bonds:reaction.bonds},color:colors[i%colors.length]}));}
  function reactionButton(reaction){const button=document.createElement('button');button.type='button';button.dataset.previewReaction=reaction.key;button.classList.toggle('active',reaction.key===focusedReactionKey);button.setAttribute('aria-pressed',String(reaction.key===focusedReactionKey));button.textContent='bonds '+reaction.bondMaps.map(edge=>edge.join('-')).join(',');button.onclick=()=>{focusedReactionKey=focusedReactionKey===reaction.key?null:reaction.key;focusedSiteKey=null;focusedAction=null;renderExplore();};return button;}
  async function refreshExplore(nextIds=selectedActionIds,inspectActionId=null,siteKey=focusedSiteKey){const revision=++requestRevision;el('reactionPreviewError').textContent='';el('reactionPreviewStatus').textContent='Validating simultaneous actions…';try{const response=await chemistry('cleavageExplore',{smiles:previewSmiles,patterns:previewDefinitions,maxActionCount:Number(el('reactionPreviewMaxActions').value),selectedActionIds:nextIds,inspectActionId,mode:el('reactionPreviewMode').value});if(revision!==requestRevision)return;explore=response;results=response;selectedActionIds=response.selectedActionIds;focusedAction=response.inspectedActionId;focusedSiteKey=siteKey;root.querySelector('.rp-grid').hidden=false;el('reactionPreviewStatus').textContent=response.actions.length+' primitive actions · '+(response.results.length?response.results.length+' generated candidates':response.availableActionIds.length+' currently valid actions')+(response.truncated?' · result limit reached':'');renderExplore();}catch(error){if(revision===requestRevision)el('reactionPreviewError').textContent=error.message;}}
  function renderExplore(){if(!explore)return;const chosen=new Set(explore.selectedActionIds),sites=exploreSites(),reactions=reactionGroups(),patterns=root.querySelector('.rp-patterns');patterns.replaceChildren();const selectedBox=document.createElement('div');selectedBox.innerHTML='<h3>Selected actions</h3>'+(explore.selectedActionIds.length?'':'<p class="muted">No actions selected.</p>');for(const id of explore.selectedActionIds){const action=explore.actions[id],row=document.createElement('div'),label=document.createElement('span'),button=document.createElement('button');row.className='rp-selected-action';label.textContent=action.patternName+' · '+action.name+' · atoms '+action.sourceAtomMaps.join(',');button.type='button';button.dataset.rpRemoveAction=id;button.textContent='Remove';button.onclick=()=>refreshExplore(explore.selectedActionIds.filter(value=>value!==id),null,focusedSiteKey);row.append(label,button);selectedBox.append(row);}patterns.append(selectedBox);root.querySelector('.rp-details').innerHTML='<p class="muted">All actions are applied simultaneously. A candidate remains available only when every selected action retains every other action’s Source match and no changed Source bond is shared.</p>';
    renderDrawing(reactionSites());const reactionList=root.querySelector('.rp-reactions');reactionList.replaceChildren();reactions.forEach(reaction=>reactionList.append(reactionButton(reaction)));if(!reactions.length)reactionList.innerHTML='<p class="rp-empty">No additional valid reaction centers.</p>';const list=root.querySelector('.rp-sites');list.replaceChildren();sites.forEach(site=>list.append(siteButton(site)));if(!focusedReactionKey)list.innerHTML='<p class="rp-empty">Select a matched reaction first.</p>';else if(!sites.length)list.innerHTML='<p class="rp-empty">No valid reactants remain for this reaction.</p>';root.querySelector('.rp-overlap').replaceChildren();const products=root.querySelector('.rp-products');products.replaceChildren();
    if(el('reactionPreviewMode').value==='exhaustive'){el('reactionPreviewProductsTitle').textContent='Generated candidates';el('reactionPreviewProductsHint').textContent='Fragments from valid unordered action sets.';products.innerHTML=explore.results.map((item,i)=>moleculeCard(item.molecule,'Candidate '+(i+1)+' · '+item.actionCount+' action'+(item.actionCount===1?'':'s'),'<p class="muted">'+escape(item.actionIds.map(id=>explore.actions[id].patternName+' · '+explore.actions[id].name).join(' + '))+'</p>'+field('Reaction SMIRKS',item.smirks))).join('')||'<p class="rp-empty">No fragment candidates were generated.</p>';return;}
    const group=exploreGroups().find(item=>item.key===focusedSiteKey);el('reactionPreviewProductsTitle').textContent=group?'Products for atoms '+group.sourceAtomMaps.join(','):'Products';el('reactionPreviewProductsHint').textContent=group?'Choose a product for the selected reactant.':'Select a matched reactant to display its products.';if(group){const choices=document.createElement('div');choices.className='rp-sites';for(const action of group.actions){const button=document.createElement('button');button.type='button';button.dataset.rpProductAction=action.id;button.classList.toggle('active',action.id===focusedAction||chosen.has(action.id));button.textContent=action.name+' · retained '+action.retainedAtomMaps.join(',');button.disabled=chosen.has(action.id);button.onclick=()=>refreshExplore(explore.selectedActionIds,action.id,focusedSiteKey);choices.append(button);}products.append(choices);}const action=explore.actions.find(a=>a.id===focusedAction);if(action&&!chosen.has(action.id)&&explore.availableActionIds.includes(action.id)){const card=document.createElement('article');card.className='rp-product';card.innerHTML='<h4>'+escape(action.patternName+' · '+action.name)+'</h4><p class="muted">Source atoms '+action.sourceAtomMaps.join(', ')+' · retained atoms '+action.retainedAtomMaps.join(', ')+'</p><button type="button" class="primary" data-rp-add-action>Add action</button>';card.querySelector('[data-rp-add-action]').onclick=()=>refreshExplore([...explore.selectedActionIds,action.id],null,focusedSiteKey);products.append(card);if(explore.candidateProduct)products.insertAdjacentHTML('beforeend',moleculeCard(explore.candidateProduct,'Fragment after adding this action'));}if(explore.selectedProduct)products.insertAdjacentHTML('beforeend',moleculeCard(explore.selectedProduct,'Current fragment · '+explore.selectedActionIds.length+' action'+(explore.selectedActionIds.length===1?'':'s')));if(!products.children.length)products.innerHTML='<p class="rp-empty">Select a matched reactant to compare its products.</p>';
  }
  el('runReactionPreview').onclick=async()=>{const button=el('runReactionPreview'),revision=++requestRevision;button.disabled=true;button.setAttribute('aria-busy','true');el('reactionPreviewError').textContent='';el('reactionPreviewStatus').textContent='Matching Reactant SMARTS…';root.querySelector('.rp-grid').hidden=true;
    try{const set=cleavageModel.cleavage_pattern_set;definitionSnapshot=JSON.stringify(set);sourceIndices=el('reactionPreviewScope').value==='set'?set.patterns.map((_,i)=>i):[Number(el('reactionPreviewTarget').value)];const patterns=sourceIndices.map(i=>set.patterns[i]);if(patterns.some(p=>!p))throw new Error('Select a Cleavage Pattern.');previewSmiles=el('reactionPreviewSmiles').value;previewDefinitions=JSON.parse(JSON.stringify(patterns));if(el('reactionPreviewMode').value!=='direct'){const maximum=Number(el('reactionPreviewMaxActions').value);if(!Number.isInteger(maximum)||maximum<1)throw new Error('Max actions must be a positive integer.');const response=await chemistry('cleavageExplore',{smiles:previewSmiles,patterns:previewDefinitions,maxActionCount:maximum,selectedActionIds:[],mode:el('reactionPreviewMode').value});if(revision!==requestRevision)return;explore=response;results=response;selectedActionIds=[];focusedAction=null;focusedSiteKey=null;focusedReactionKey=null;root.querySelector('.rp-grid').hidden=false;el('reactionPreviewStatus').textContent=response.actions.length+' primitive actions · '+(response.results.length?response.results.length+' generated candidates':response.availableActionIds.length+' currently valid candidates')+(response.truncated?' · result limit reached':'');renderExplore();return;}const response=await chemistry('reactionPreview',{smiles:previewSmiles,patterns:previewDefinitions});if(revision!==requestRevision)return;results=response;filter=response.patterns.length===1?0:-1;selected=null;root.querySelector('.rp-grid').hidden=false;el('reactionPreviewProductsHint').textContent='Direct products for the selected match';el('reactionPreviewStatus').textContent=response.patterns.length+' patterns · '+allSites().length+' matched sites'+(response.truncated?' · Preview limit reached; some matches or products are omitted.':'');renderResults();}catch(error){if(revision===requestRevision){results=null;explore=null;el('reactionPreviewError').textContent=error.message;el('reactionPreviewStatus').textContent='';}}finally{button.disabled=false;button.removeAttribute('aria-busy');}};
  el('reactionPreviewSmiles').onkeydown=event=>{if(event.key==='Enter'&&!el('runReactionPreview').disabled){event.preventDefault();el('runReactionPreview').click();}};
  renderCleavage();
}
exports.script=()=>`(${installReactionPreview.toString()})();`;
