/* Enhances the Workbench's existing renderer and chemistry messaging. */
function installCleavageEditor(periodicRows) {
  const el=id=>document.getElementById(id), root=el('visualBuilder');
  const style=document.createElement('style');
  style.textContent=`
  button{transition:filter 100ms ease,transform 100ms ease,box-shadow 100ms ease}button:not(:disabled):hover{filter:brightness(1.12)}button:not(:disabled):active,button.ce-clicked{filter:brightness(1.3);transform:translateY(1px);box-shadow:inset 0 2px 5px #0007!important}button:focus-visible{outline:2px solid var(--vscode-focusBorder,#67caff);outline-offset:2px}button[aria-busy="true"]{cursor:progress;opacity:.8}button[aria-busy="true"]::after{content:"";display:inline-block;width:10px;height:10px;border:2px solid currentColor;border-right-color:transparent;border-radius:50%;margin-left:8px;vertical-align:middle;animation:ce-spin .7s linear infinite}@keyframes ce-spin{to{transform:rotate(360deg)}}@media(prefers-reduced-motion:reduce){button{transition:none}button[aria-busy="true"]::after{animation:none}}
  #visualBuilder{padding:14px;background:linear-gradient(135deg,#071d2b,#101b28);border:1px solid #215375;border-radius:10px;color:#d7e9f7}
  #visualBuilder .muted{margin:4px 0;color:#91afc5}#visualBuilder h2{color:#89d6ff}#visualBuilder h3{font-size:13px;margin:0 0 12px;color:#89d6ff}
  .ce-step{border:1px solid #245473;border-radius:8px;margin-top:12px;overflow:hidden}.ce-header{display:flex;align-items:center;gap:12px;padding:12px;background:#0d2638;cursor:pointer}.ce-header button{background:transparent;border:0;color:inherit;text-align:left;flex:1;font-size:15px;font-weight:600}.ce-number{display:grid;place-items:center;border:2px solid #149cf5;border-radius:50%;width:30px;height:30px;color:#46b8ff}.ce-status{font-size:11px;border:1px solid #2d6e97;border-radius:20px;padding:4px 10px;color:#90ccf1}.ce-status.done{color:#5de28a;border-color:#258a50}
  .ce-body{padding:12px}.ce-columns{display:grid;grid-template-columns:minmax(0,1.35fr) minmax(280px,1fr);gap:12px}.ce-panel{background:#0b202e;border:1px solid #25465d;border-radius:7px;padding:12px;margin-bottom:10px}.ce-toolbar{display:flex;align-items:center;gap:6px;padding:0 0 10px}.ce-toolbar .muted{margin-left:auto;font-size:11px}.ce-icon{width:34px;height:32px;display:inline-grid;place-items:center;padding:6px!important;border-radius:5px!important}.ce-icon svg{width:18px;height:18px;fill:none;stroke:currentColor;stroke-width:1.7;stroke-linecap:round;stroke-linejoin:round}.ce-icon.active{background:#0866a6!important;border-color:#27b6ff!important;color:white}.ce-divider{width:1px;height:20px;background:#2e5068;margin:0 5px}
  #visualBuilder .molecule-canvas{background:var(--vscode-editor-background,#1e1e1e);color:var(--vscode-editor-foreground,#ddd);border:1px solid #29506b;border-radius:7px;min-height:320px}#visualBuilder .molecule-canvas svg{width:100%;height:350px;touch-action:none}#visualBuilder .mol-atom.selected .atom-label-bg{stroke:#24afff;stroke-width:3;filter:drop-shadow(0 0 5px #149cff)}#visualBuilder .bond-group.selected line:not(.bond-hit){stroke:#37b6ff;filter:drop-shadow(0 0 3px #149cff)}#visualBuilder .mol-atom:hover .atom-label-bg{stroke:#8cd7ff}#visualBuilder .bond-group:hover line:not(.bond-hit){stroke:#8cd7ff}.ce-added line:not(.bond-hit){stroke:#4ddd86!important}
  .ce-chips{display:flex;flex-wrap:wrap;gap:5px;align-items:center;margin:8px 0}.ce-chip{display:inline-flex;align-items:center;gap:6px;background:#12354d;border:1px solid #2a6184;border-radius:5px;padding:4px 8px;font-size:11px}.ce-chip button{border:0;background:none;color:#b1d7ed;padding:0;cursor:pointer}.ce-options{display:flex;gap:12px;flex-wrap:wrap;margin:10px 0}.ce-options label{display:flex;align-items:center;gap:5px;font-size:12px}.ce-options input{width:auto;margin:0;accent-color:#139eff}.ce-output{display:flex;align-items:center;gap:8px;margin-top:10px}.ce-output input{flex:1;min-width:0;font-family:monospace;font-size:12px;background:#0c2638}.ce-summary{font-family:monospace;font-size:11px;max-width:45%;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.ce-counts{font-size:11px;color:#93c5e6}.ce-error{color:#ff9292;margin:8px 0}.ce-apply{width:100%;margin-top:12px;padding:10px!important;background:#087de1!important;color:white!important}.ce-periodic{display:grid;grid-template-columns:repeat(18,minmax(30px,1fr));min-width:650px;gap:4px}.ce-periodic button{padding:5px 0;font-size:11px}.ce-periodic button.active{background:#087ddd!important;color:white!important;border-color:#67caff!important;outline:2px solid #67caff;outline-offset:-2px;box-shadow:0 0 6px #138de577}.ce-periodic button.mixed{border-color:#67caff!important;background:#24506b!important}.ce-products{display:flex;flex-wrap:wrap;gap:6px;margin-bottom:12px}.ce-product-item{display:flex;align-items:center;gap:4px}.ce-product-actions{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px;margin-top:12px}.ce-product-actions[hidden]{display:none}.ce-product-actions button{width:100%;min-height:40px;margin:0!important;padding:10px!important;box-sizing:border-box;font-size:13px}.ce-products button.active{background:#0866a6!important;border-color:#27b6ff!important;color:white}.ce-help{font-size:11px;color:#a4c4db;margin:0 0 10px}.ce-dialog{background:#0c2233;color:#d7e9f7;border:1px solid #299bdf;border-radius:10px;max-width:90vw;width:820px}.ce-periodic-wrap{overflow-x:auto;padding:3px}.ce-dialog::backdrop{background:#0009}
  @media(max-width:1000px){.ce-columns{grid-template-columns:1fr}.ce-summary{max-width:30%}}@media(max-width:600px){.ce-toolbar .muted{display:none}}
  `;document.head.append(style);
  const clickTimers=new WeakMap();
  function acknowledgeButton(event){const button=event.target.closest?.('button');if(!button||button.disabled)return;clearTimeout(clickTimers.get(button));button.classList.add('ce-clicked');clickTimers.set(button,setTimeout(()=>button.classList.remove('ce-clicked'),220));}
  document.addEventListener('pointerdown',acknowledgeButton,true);document.addEventListener('click',acknowledgeButton,true);
  function busyAction(button,action,disable=true){return async event=>{if(disable&&button.getAttribute('aria-busy')==='true')return;const disabled=button.disabled;button.setAttribute('aria-busy','true');if(disable)button.disabled=true;try{return await action(event);}finally{button.removeAttribute('aria-busy');if(disable)button.disabled=disabled;}};}
  const paths={undo:'M8 4L3 9l5 5 M3 9h10a7 7 0 0 1 0 14',select:'M4 3l13 10-7 1-3 7z',edit:'M4 16l-1 5 5-1L20 8l-4-4z M14 6l4 4',lasso:'M18 17c5-3 3-12-5-13S1 9 3 14s10 7 11 3-5-4-4 1 7 4 10 1',box:'M3 3h5m3 0h5m3 0h2v5m0 3v5m0 3v2h-5m-3 0H8m-3 0H3v-5m0-3V8m0-3V3',clear:'M4 6h16 M9 6V3h6v3 M6 6l1 15h10l1-15 M10 10v7m4-7v7',copy:'M8 8h12v13H8z M16 8V3H3v13h5',plus:'M12 4v16 M4 12h16',minus:'M4 12h16',fit:'M3 8V3h5 M16 3h5v5 M21 16v5h-5 M8 21H3v-5',cut:'M9 9l12 12 M9 15L21 3 M7 6a3 3 0 1 0 0 .1 M7 18a3 3 0 1 0 0 .1',bond:'M4 9h16 M4 15h16',atom:'M12 3l9 5v8l-9 5-9-5V8z'};
  function icon(name,title,attrs=''){return '<button type="button" class="ce-icon" title="'+title+'" aria-label="'+title+'" '+attrs+'><svg viewBox="0 0 24 24" aria-hidden="true"><path d="'+paths[name]+'"/></svg></button>';}
  function node(html){const t=document.createElement('template');t.innerHTML=html;return t.content.firstElementChild;}
  const builderHome=document.createComment('Visual editor home');root.before(builderHome);
  let activePattern=null;
  function placeBuilder(){
    const patterns=cleavageModel.cleavage_pattern_set.patterns;
    const index=activePattern&&patterns[visualPatternIndex]===activePattern?visualPatternIndex:patterns.indexOf(activePattern);
    const card=index<0?null:el('cleavagePatterns').children[index];
    if(card){card.append(root);visualPatternIndex=index;}
    else builderHome.after(root);
    root.after(registerStatus);
    root.querySelector('h2').textContent=index<0?'Cleavage Pattern Editor':'Cleavage Pattern Editor (Pattern '+(index+1)+')';
  }
  const baseRenderCleavage=renderCleavage;
  renderCleavage=()=>{
    // Preserve the editor DOM and its handlers when the pattern cards are rebuilt.
    builderHome.after(root);
    if(activePattern&&!cleavageModel.cleavage_pattern_set.patterns.includes(activePattern)){resetVisualBuilder();root.hidden=true;}
    baseRenderCleavage();placeBuilder();
  };
  const oldTitle=root.querySelector('.section-title');oldTitle.querySelector('h2').textContent='Cleavage Pattern Editor';oldTitle.querySelector('p').textContent='Build reactant queries and edit mapped products.';
  el('clearSelection').remove();oldTitle.querySelector('.actions').prepend(node(icon('clear','Clear selection','id="clearSelection"')));el('closeBuilder').textContent='×';el('closeBuilder').title='Close editor';el('closeBuilder').setAttribute('aria-label','Close editor');
  const step1=node('<div class="ce-step"><div class="ce-header"><span class="ce-number">1</span><button type="button" aria-expanded="true">Step 1: Reactant SMARTS Builder</button><span class="ce-summary"></span><span class="ce-status">In progress</span></div><div class="ce-body"><div class="ce-columns"><div class="ce-left"></div><div class="ce-right"></div></div><p class="ce-error" role="alert"></p></div></div>');root.append(step1);
  const step2=node('<div class="ce-step"><div class="ce-header"><span class="ce-number">2</span><button type="button" aria-expanded="false">Step 2: Reaction / Product Editor</button><span class="ce-status">Waiting</span></div><div class="ce-body" hidden><div class="ce-columns"><div class="ce-left"></div><div class="ce-right"></div></div><p class="ce-error" role="alert"></p></div></div>');root.append(step2);
  const step3=node('<div class="ce-step"><div class="ce-header"><span class="ce-number">3</span><button type="button" aria-expanded="false">Step 3: Add Cleavage Pattern to Set</button><span class="ce-status">Waiting</span></div><div class="ce-body" hidden><div class="ce-panel" id="cleavagePatternSummary"></div><p class="ce-error" role="alert"></p></div></div>');root.append(step3);
  const body1=step1.querySelector('.ce-body'),body2=step2.querySelector('.ce-body'),body3=step3.querySelector('.ce-body');
  const left1=step1.querySelector('.ce-left'),right1=step1.querySelector('.ce-right'),left2=step2.querySelector('.ce-left'),right2=step2.querySelector('.ce-right');
  left1.append(el('moleculeCanvas'));el('atomConstraints').parentElement.parentElement.remove();
  left1.append(el('builderPatternName').closest('label'));right1.append(el('applyReactant'));el('applyReactant').textContent='Apply →';el('applyReactant').classList.add('ce-apply');
  const productContainer=el('productBuilder');productContainer.querySelector('h3').remove();productContainer.querySelector('p').remove();left2.append(productContainer);
  const productDrawing=node('<div><h3>Product</h3></div>');productContainer.insertBefore(productDrawing,el('productCanvas'));productDrawing.append(el('productCanvas'));el('productAtomTools').remove();el('productBondTools').remove();el('builderProductSource').closest('.row').remove();el('allowProductAtomTypes').closest('label').remove();productContainer.hidden=false;
  const productList=node('<div class="ce-products" aria-label="Products"></div>');productContainer.prepend(productList);
  el('builderProductSelect').closest('label').hidden=true;
  const addProductButton=el('newVisualProduct');addProductButton.classList.add('ce-icon');addProductButton.innerHTML=icon('plus','Add product').replace(/^<button[^>]*>|<\/button>$/g,'');addProductButton.title='Add product';addProductButton.setAttribute('aria-label','Add product');productList.append(addProductButton);el('builderProductSelect').closest('.row').remove();

  const editors=[{canvas:el('moleculeCanvas'),left:left1,right:right1,step:step1,mode:'selection',shape:'lasso',atoms:()=>selectedAtoms,bonds:()=>selectedBonds,graph:()=>molGraph,render:()=>renderMolecule(),layout:()=>layout(),atomState:()=>atomConstraintState,bondState:()=>bondConstraintState,product:false,view:[0,0,700,440]}, {canvas:el('productCanvas'),left:productDrawing,right:right2,step:step2,mode:'selection',shape:'lasso',atoms:()=>productSelectedAtoms,bonds:()=>productSelectedBonds,graph:()=>productGraph,render:()=>renderProduct(),layout:()=>productLayout(),atomState:()=>productConstraints,bondState:()=>productBondConstraints,product:true,view:[0,0,700,440]}];
  let productSelectedBonds=new Set(),productConstraints={},productBondConstraints={},completed=false,reactantText='',productText='',draftPattern=null,productStats=new Map(),generation=0,timer,productDrafts=new Map(),productLoadRevision=0,productHistory=[],productBondQueries={};
  // One scale on both axes preserves RDKit angles and relative bond lengths.
  function rdkitLayout(graph){const xs=graph.atoms.map(a=>a.x),ys=graph.atoms.map(a=>a.y),cx=(Math.min(...xs)+Math.max(...xs))/2,cy=(Math.min(...ys)+Math.max(...ys))/2;return {x:a=>350+(a.x-cx)*65,y:a=>220+(a.y-cy)*65};}
  layout=()=>rdkitLayout(molGraph);productLayout=()=>rdkitLayout(productGraph);
  function fitView(ed){const graph=ed.graph();if(!graph)return [0,0,700,440];const l=ed.layout(),xs=graph.atoms.map(l.x),ys=graph.atoms.map(l.y),width=Math.max(700,Math.max(...xs)-Math.min(...xs)+140),height=Math.max(440,Math.max(...ys)-Math.min(...ys)+140),w=Math.max(width,height*700/440);return [350-w/2,220-w*440/700/2,w,w*440/700];}
  function productSnapshot(){return JSON.stringify({productAtomMaps,productAtomOverrides,productBondOverrides,deletedAtoms:[...productDeletedAtoms],productAddedBonds,productConstraints,productBondConstraints,productBondQueries,selectedAtoms:[...productSelectedAtoms],selectedBonds:[...productSelectedBonds],nextProductBondId});}
  function restoreProductSnapshot(raw){const state=JSON.parse(raw);productAtomMaps=state.productAtomMaps;productAtomOverrides=state.productAtomOverrides;productBondOverrides=state.productBondOverrides;productDeletedAtoms=new Set(state.deletedAtoms);productAddedBonds=state.productAddedBonds;productConstraints=state.productConstraints;productBondConstraints=state.productBondConstraints;productBondQueries=state.productBondQueries;productSelectedAtoms=new Set(state.selectedAtoms);productSelectedBonds=new Set(state.selectedBonds);nextProductBondId=state.nextProductBondId;}
  function productFingerprint(){const payload=productPayload();payload.atoms.sort((a,b)=>a-b);payload.bonds.sort((a,b)=>a-b);return JSON.stringify({name:el('builderProductName').value.trim(),payload});}
  function stashProduct(){const product=draftPattern?.products[visualProductIndex];if(!product)return;let draft=productDrafts.get(product);if(!draft){draft={baseline:productFingerprint()};productDrafts.set(product,draft);}draft.state=productSnapshot();draft.name=el('builderProductName').value;draft.text=productText;draft.history=productHistory.slice();draft.dirty=draft.baseline!==productFingerprint();}
  el('builderProductName').addEventListener('input',()=>{++generation;stashProduct();paintProductList();registerStatus.textContent='';});
  function rememberProduct(){registerStatus.textContent='';productHistory.push(JSON.stringify({productAtomMaps,productAtomOverrides,productBondOverrides,deletedAtoms:[...productDeletedAtoms],productAddedBonds,productConstraints,productBondConstraints,productBondQueries,selectedAtoms:[...productSelectedAtoms],selectedBonds:[...productSelectedBonds],nextProductBondId}));}
  function undoProduct(){const previous=productHistory.pop();if(!previous)return;const state=JSON.parse(previous);productAtomMaps=state.productAtomMaps;productAtomOverrides=state.productAtomOverrides;productBondOverrides=state.productBondOverrides;productDeletedAtoms=new Set(state.deletedAtoms);productAddedBonds=state.productAddedBonds;productConstraints=state.productConstraints;productBondConstraints=state.productBondConstraints;productBondQueries=state.productBondQueries;productSelectedAtoms=new Set(state.selectedAtoms);productSelectedBonds=new Set(state.selectedBonds);nextProductBondId=state.nextProductBondId;productBondStart=null;renderProduct();}
  function output(label){const n=node('<div class="ce-output"><b style="font-size:11px">'+label+'</b><input readonly aria-label="'+label+'">'+icon('copy','Copy '+label)+'</div>');n.querySelector('button').onclick=()=>{vscode.postMessage({type:'copyCleavageText',text:n.querySelector('input').value});};return n;}
  const reactantOutput=output('Reactant SMARTS');left1.append(reactantOutput);const productOutput=output('Product SMARTS'),reactionOutput=output('Reaction SMIRKS');right2.append(productOutput,reactionOutput);
  const summaryCounts=node('<span class="ce-counts"></span>');step1.querySelector('.ce-header').append(summaryCounts);
  const summaryCopy=node(icon('copy','Copy Reactant SMARTS'));step1.querySelector('.ce-header').append(summaryCopy);summaryCopy.hidden=true;summaryCopy.onclick=e=>{e.stopPropagation();vscode.postMessage({type:'copyCleavageText',text:reactantText});};
  function paintPatternSummary(){const products=draftPattern?.products||[];el('cleavagePatternSummary').textContent=(el('builderPatternName').value.trim()||'Untitled pattern')+' · '+products.length+' products'+(products.some(p=>productDrafts.get(p)?.dirty)?' · Unsaved product changes':'');step3.querySelector('.ce-status').textContent=completed?'Ready':'Waiting';}
  function openStep(index){[body1,body2,body3].forEach((body,i)=>{body.hidden=i!==index;[step1,step2,step3][i].querySelector('.ce-header button').setAttribute('aria-expanded',String(i===index));});if(index===2){stashProduct();paintPatternSummary();body3.querySelector('.ce-error').textContent='';}if(!root.hidden)jumpToCleavage([step1,step2,step3][index]);}
  step1.querySelector('.ce-header').onclick=()=>openStep(0);step2.querySelector('.ce-header').onclick=()=>{if(completed)openStep(1);};step3.querySelector('.ce-header').onclick=()=>{if(completed)openStep(2);};
  const operations=node('<div class="ce-panel ce-counts"></div>');right2.insertBefore(operations,productOutput);
  function showOutputs(){summaryCounts.textContent=completed?selectedAtoms.size+' atoms · '+selectedBonds.size+' bonds':'';reactantOutput.querySelector('input').value=reactantText;step1.querySelector('.ce-summary').textContent=completed?reactantText:'';productOutput.querySelector('input').value=productText;reactionOutput.querySelector('input').value=productText?reactantText+'>>'+productText:'';operations.textContent='Added bonds: '+productAddedBonds.length+' · Changed bonds: '+Object.keys(productBondOverrides).length;}
  function graphStats(graph,atoms=new Set(graph.atoms.map(a=>a.index)),bonds=graph.bonds){
    const links=new Map([...atoms].map(id=>[id,[]])),edges=bonds.filter(b=>atoms.has(b.begin)&&atoms.has(b.end));edges.forEach(b=>{links.get(b.begin).push(b.end);links.get(b.end).push(b.begin);});let molecules=0;const visited=new Set();for(const id of atoms){if(visited.has(id))continue;molecules++;const stack=[id];while(stack.length){const current=stack.pop();if(visited.has(current))continue;visited.add(current);stack.push(...links.get(current));}}return {atoms:atoms.size,bonds:edges.length,molecules};
  }
  function deselectAtom(ed,id){ed.atoms().delete(id);for(const bondId of [...ed.bonds()]){const bond=getBond(ed,bondId);if(bond&&(bond.begin===id||bond.end===id))ed.bonds().delete(bondId);}if(ed.focusAtom===id)ed.focusAtom=null;if(ed.focusBond!==null&&!ed.bonds().has(ed.focusBond))ed.focusBond=null;}
  function selectionStats(ed){return graphStats(ed.graph(),ed.atoms(),[...ed.bonds()].map(id=>getBond(ed,id)).filter(Boolean));}
  function error(ed,message){ed.step.querySelector('.ce-error').textContent=message;}
  async function refreshOutputs(){const revision=++generation;clearTimeout(timer);timer=setTimeout(async()=>{try{if(!molGraph||!selectedAtoms.size){reactantText='';showOutputs();return;}if(!completed){const r=await chemistry('reactant',{...sourcePayload(),atoms:[...selectedAtoms],bonds:[...selectedBonds],constraints:atomConstraintState,bondConstraints:bondConstraintState,atomMapBySource});if(revision!==generation)return;reactantText=r.smarts;error(editors[0],'');}if(completed&&productGraph){const r=await chemistry('productFromSelection',productPayload());if(revision!==generation)return;productText=r.smarts;stashProduct();error(editors[1],'');}showOutputs();}catch(e){if(revision===generation){if(completed)productText='';else reactantText='';showOutputs();error(editors[completed?1:0],e.message);}}},180);}
  function productPayload(){return {reactantSmarts:reactantText,atoms:[...productSelectedAtoms],bonds:[...productSelectedBonds].filter(id=>typeof id==='number'),atomOverrides:productAtomOverrides,bondOverrides:productBondOverrides,bondQueries:productBondQueries,addedBonds:productAddedBonds.map(b=>({...b,selected:productSelectedBonds.has('added:'+b.id)}))};}

  function getBond(ed,id){return typeof id==='string'?productAddedBonds.find(b=>'added:'+b.id===id):ed.graph().bonds[id];}
  function bondOrder(ed,id){if(typeof id==='string')return String(getBond(ed,id).order);return productBondOverrides[id]&&productBondOverrides[id]!=='remove'?productBondOverrides[id]:String(getBond(ed,id).order);}
  function defaultAtom(a){const query=String(a.smarts||'').replace(/:\d+(?=\])/g,'');if(query==='*'||query==='[*]')return {mode:'any',elements:[],nonHydrogen:false};if(query==='[!#1]')return {mode:'any',elements:[],nonHydrogen:true};if(/^\[!#\d+(?:[;&]!#\d+)*\]$/.test(query)){const numbers=[...query.matchAll(/!#(\d+)/g)].map(m=>Number(m[1]));return {mode:'elements',excludeElements:true,elements:numbers.filter(n=>n!==1).map(n=>elementSymbols[n-1]),nonHydrogen:numbers.includes(1)};}if(query.startsWith('['))return {mode:'custom',smarts:query.replace(/;!#1(?=\])/g,''),elements:a.symbol==='*'?[]:[a.symbol],nonHydrogen:query.includes('!#1')};return {mode:'elements',elements:[a.symbol],nonHydrogen:true};}
  function defaultBond(b){const symbols={'-':'single','=':'double','#':'triple',':':'aromatic'},types=String(b.smarts||'').split(';')[0].split(',').map(x=>symbols[x]).filter(Boolean);return {mode:'custom',types:types.length?types:[sourceBondType({...b,order:Number(b.order)})],ringStatus:b.smarts?.includes('!@')?'notInRing':b.smarts?.includes('@')?'inRing':b.inRing?'inRing':'notInRing'};}
  function invalidateReactant(){registerStatus.textContent='';completed=false;step1.querySelector('.ce-status').textContent='In progress';step1.querySelector('.ce-status').classList.remove('done');}
  function applyConstraint(ed,kind,fn){if(!ed.product)invalidateReactant();if(ed.product)rememberProduct();const focus=kind==='atom'?ed.focusAtom:ed.focusBond,ids=ed.mode==='edit'?(focus===null||focus===undefined?[]:[focus]):kind==='atom'?ed.atoms():ed.bonds(),states=kind==='atom'?ed.atomState():ed.bondState(),graph=ed.graph();ids.forEach(id=>{const state=states[id]||(states[id]=kind==='atom'?defaultAtom(graph.atoms[id]):defaultBond(getBond(ed,id)));fn(state);if(ed.product&&kind==='bond'&&state.mode!=='any'&&state.types.length===1&&productBondOverrides[id]!=='remove'){const order={single:'1',double:'2',triple:'3',aromatic:'1.5'}[state.types[0]];if(typeof id==='string')getBond(ed,id).order=order;else productBondOverrides[id]=order;}if(ed.product&&kind==='atom')productAtomOverrides[id]=state.mode==='any'?(state.nonHydrogen===false?'[*]':'[!#1]'):state.mode==='custom'?(state.nonHydrogen?'['+String(state.smarts).replace(/^\[|\]$/g,'')+';!#1]':state.smarts):'['+(state.elements.length?state.elements.map(s=>(state.excludeElements?'!#':'#')+elementNumbers[s]).join(state.excludeElements?';':','):'*')+(state.nonHydrogen?';!#1':'')+']';});ed.render();}
  const elementSymbols='H He Li Be B C N O F Ne Na Mg Al Si P S Cl Ar K Ca Sc Ti V Cr Mn Fe Co Ni Cu Zn Ga Ge As Se Br Kr Rb Sr Y Zr Nb Mo Tc Ru Rh Pd Ag Cd In Sn Sb Te I Xe Cs Ba La Ce Pr Nd Pm Sm Eu Gd Tb Dy Ho Er Tm Yb Lu Hf Ta W Re Os Ir Pt Au Hg Tl Pb Bi Po At Rn Fr Ra Ac Th Pa U Np Pu Am Cm Bk Cf Es Fm Md No Lr Rf Db Sg Bh Hs Mt Ds Rg Cn Nh Fl Mc Lv Ts Og'.split(' '),elementNumbers=Object.fromEntries(elementSymbols.map((s,i)=>[s,i+1]));
  const dialog=node('<dialog class="ce-dialog"><h3>Periodic Table</h3><div class="ce-periodic-wrap"><div class="ce-periodic"></div></div><div class="actions"><button type="button">Done</button></div></dialog>');root.append(dialog);dialog.querySelector('.actions button').onclick=()=>dialog.close();let periodicEditor;
  periodicRows.forEach((row,ri)=>row.forEach((s,ci)=>{if(!s){const gap=document.createElement('span');gap.style.gridRow=String(ri+1);gap.style.gridColumn=String(ci+1);dialog.querySelector('.ce-periodic').append(gap);return;}const b=node('<button type="button" data-element="'+s+'">'+s+'</button>');b.style.gridRow=String(ri+1);b.style.gridColumn=String(ci+1);b.onclick=()=>{const remove=periodicStates().every(state=>(state.elements||[]).includes(s));applyConstraint(periodicEditor,'atom',state=>{state.mode='elements';state.elements=state.elements||[];state.elements=remove?state.elements.filter(x=>x!==s):[...new Set([...state.elements,s])];});paintPeriodic();};dialog.querySelector('.ce-periodic').append(b);}));
  function periodicStates(){const ids=periodicEditor.mode==='edit'?[periodicEditor.focusAtom]:[...periodicEditor.atoms()];return ids.map(id=>periodicEditor.atomState()[id]||(periodicEditor.atomState()[id]=defaultAtom(periodicEditor.graph().atoms[id])));}
  function paintPeriodic(){const states=periodicStates();dialog.querySelectorAll('.ce-periodic button').forEach(b=>{const selected=states.every(s=>(s.elements||[]).includes(b.textContent)),mixed=!selected&&states.some(s=>(s.elements||[]).includes(b.textContent));b.classList.toggle('active',selected);b.classList.toggle('mixed',mixed);b.setAttribute('aria-pressed',selected?'true':mixed?'mixed':'false');});}

  function inspector(ed){const graph=ed.graph(),atoms=ed.atoms(),bonds=ed.bonds();if(!graph)return;[...bonds].forEach(id=>{if(!getBond(ed,id))bonds.delete(id);});ed.selected.innerHTML='<div class="ce-chips"><b>Atoms ('+atoms.size+')</b>'+[...atoms].map(i=>'<span class="ce-chip">Atom '+(i+1)+' ('+graph.atoms[i].symbol+') <button data-remove-atom="'+i+'" aria-label="Deselect atom '+(i+1)+'">×</button></span>').join('')+'</div><div class="ce-chips"><b>Bonds ('+bonds.size+')</b>'+[...bonds].map(i=>{const b=getBond(ed,i);return '<span class="ce-chip">Bond '+(b.begin+1)+'–'+(b.end+1)+' <button data-remove-bond="'+i+'" aria-label="Deselect bond">×</button></span>';}).join('')+'</div>';const stats=selectionStats(ed);ed.counts.textContent=atoms.size+' atoms · '+(ed.product?stats.bonds:bonds.size)+' bonds'+(ed.product?' · '+stats.molecules+' molecules':'');
    if(!atoms.has(ed.focusAtom))ed.focusAtom=null;if(!bonds.has(ed.focusBond))ed.focusBond=null;const aid=ed.mode==='edit'?(ed.focusAtom??undefined):[...atoms][0],bid=ed.mode==='edit'?(ed.focusBond??undefined):[...bonds][0];const a=aid===undefined?null:(ed.atomState()[aid]||(ed.product?{mode:'preserve'}:ed.atomState()[aid]=defaultAtom(graph.atoms[aid]))),b=bid===undefined?null:(ed.bondState()[bid]||(ed.product?{mode:'preserve'}:ed.bondState()[bid]=defaultBond(getBond(ed,bid))));
    if(ed.product){productInspector(ed,aid,bid);return;}
    ed.atomPanel.innerHTML='<h3>Atom Constraints</h3>'+(a?'<div class="ce-options"><label><input type="radio" name="atomMode'+ed.product+'" data-am="any" '+(a.mode==='any'?'checked':'')+'>Any</label><label><input type="radio" name="atomMode'+ed.product+'" data-am="elements" '+(a.mode!=='any'?'checked':'')+'>Custom</label></div>'+(a.mode==='any'?'':'<div class="ce-options"><label><input type="checkbox" data-exclude-elements '+(a.excludeElements?'checked':'')+'>Exclude selected elements (NOT)</label></div><div class="ce-chips"><span>'+(a.excludeElements?'Excluded elements':'Allowed elements (OR)')+'</span>'+(a.elements||[]).map(s=>'<span class="ce-chip">'+s+' <button data-element-remove="'+s+'" aria-label="Remove '+s+'">×</button></span>').join('')+'<button type="button" data-periodic title="Open periodic table" aria-label="Open periodic table">＋</button></div>'+(a.mode==='custom'?'<label>Existing atom SMARTS<input data-existing-query value="'+htmlEscape(a.smarts||'')+'"></label>':''))+'<div class="ce-options"><label><input type="checkbox" data-non-h '+(a.nonHydrogen!==false?'checked':'')+'>Non-H</label></div>':'<p class="muted">Select an atom, then click it in Edit mode to edit matching rules.</p>');
    ed.bondPanel.innerHTML='<h3>Bond Constraints</h3>'+(b?'<div class="ce-options"><label><input type="radio" name="bondMode'+ed.product+'" data-bm="any" '+(b.mode==='any'?'checked':'')+'>Any</label><label><input type="radio" name="bondMode'+ed.product+'" data-bm="custom" '+(b.mode!=='any'?'checked':'')+'>Custom</label></div>'+(b.mode==='any'?'':'<div class="ce-options">'+['single','double','triple','aromatic'].map(t=>'<label><input type="checkbox" data-bt="'+t+'" '+(b.types.includes(t)?'checked':'')+'>'+t[0].toUpperCase()+t.slice(1)+'</label>').join('')+'</div><div class="ce-options"><span>Ring status</span>'+[['any','Any'],['inRing','In ring'],['notInRing','Not in ring']].map(([v,l])=>'<label><input type="radio" name="ring'+ed.product+'" data-rs="'+v+'" '+((b.ringStatus||(b.ring?'inRing':'notInRing'))===v?'checked':'')+'>'+l+'</label>').join('')+'</div>'):'<p class="muted">Select a bond, then click it in Edit mode to edit matching rules.</p>');
    ed.bondPanel.onchange=e=>{const d=e.target.dataset;applyConstraint(ed,'bond',s=>{if(d.bm)s.mode=d.bm;if(d.bt)s.types=e.target.checked?[...new Set([...s.types,d.bt])]:s.types.filter(t=>t!==d.bt);if(d.rs)s.ringStatus=d.rs;});};
    ed.atomPanel.onchange=e=>{const d=e.target.dataset;applyConstraint(ed,'atom',s=>{if(d.am){s.mode=d.am;s.elements=s.elements||[graph.atoms[aid].symbol];}if(d.excludeElements!==undefined){s.excludeElements=e.target.checked;s.mode='elements';}if(d.nonH!==undefined)s.nonHydrogen=e.target.checked;if(d.existingQuery!==undefined){s.mode='custom';s.smarts=e.target.value;s.excludeElements=false;}});};
    ed.atomPanel.onclick=e=>{if(e.target.dataset.periodic!==undefined){periodicEditor=ed;paintPeriodic();dialog.showModal();}if(e.target.dataset.elementRemove)applyConstraint(ed,'atom',s=>{s.mode='elements';s.elements=s.elements.filter(x=>x!==e.target.dataset.elementRemove);});};
  }
  function productInspector(ed,aid,bid){
    const atom=aid===undefined?null:productGraph.atoms[aid],changed=atom&&productAtomOverrides[aid]!==undefined;
    ed.atomPanel.innerHTML='<h3>Product atom</h3>'+(atom?'<div class="ce-options"><label><input type="radio" name="productAtomMode" data-atom-keep '+(!changed?'checked':'')+'>Unchanged</label><label><input type="radio" name="productAtomMode" data-atom-change '+(changed?'checked':'')+'>Custom</label></div><p class="muted">Atom map '+productAtomMaps[aid]+'</p>'+(changed?'<label>Atom SMARTS<input data-product-query value="'+htmlEscape(productAtomOverrides[aid])+'"></label><div class="ce-chips">'+(productConstraints[aid]?.elements||[]).map(symbol=>'<span class="ce-chip">'+symbol+'</span>').join('')+'<button type="button" data-periodic title="Open periodic table" aria-label="Open periodic table">＋</button></div>':''):'<p class="muted">Select an atom and click it in Edit mode.</p>');
    ed.atomPanel.onchange=e=>{if(e.target.dataset.atomKeep!==undefined){rememberProduct();delete productAtomOverrides[aid];delete productConstraints[aid];ed.render();}else if(e.target.dataset.atomChange!==undefined){rememberProduct();productAtomOverrides[aid]=String(atom.smarts||atom.symbol).replace(/:\d+(?=\])/g,'');productConstraints[aid]=defaultAtom(atom);ed.render();}else if(e.target.dataset.productQuery!==undefined){rememberProduct();productAtomOverrides[aid]=e.target.value;productConstraints[aid]={mode:'custom',smarts:e.target.value,elements:[]};ed.render();}};
    ed.atomPanel.onclick=e=>{if(e.target.dataset.periodic!==undefined){periodicEditor=ed;paintPeriodic();dialog.showModal();}};
    const bond=bid===undefined?null:getBond(ed,bid),order=bond?bondOrder(ed,bid):null;
    const overridden=typeof bid==='string'?true:productBondOverrides[bid]!==undefined||productBondQueries[bid]!==undefined;
    ed.bondPanel.innerHTML='<h3>Product bond</h3>'+(bond?'<div class="ce-options">'+[...(typeof bid==='string'?[]:[['preserve','Unchanged']]),['1','Single'],['2','Double'],['3','Triple'],['1.5','Aromatic']].map(([value,label])=>'<label><input type="radio" name="productOrder" data-product-order="'+value+'" '+((value==='preserve'?!overridden:overridden&&order===value)?'checked':'')+'>'+label+'</label>').join('')+'</div><p class="muted">'+(typeof bid==='string'?'Choose the type of the added bond.':'Unchanged keeps the current atom and bond queries.')+'</p>':'<p class="muted">Select a bond and click it in Edit mode.</p>');
    if(typeof bid==='string')ed.bondPanel.append(node(icon('clear','Remove added bond','data-remove-added-bond')));ed.bondPanel.onclick=e=>{if(e.target.closest('[data-remove-added-bond]')){rememberProduct();productAddedBonds=productAddedBonds.filter(b=>'added:'+b.id!==bid);productSelectedBonds.delete(bid);delete productBondConstraints[bid];ed.focusBond=null;ed.render();}};
    ed.bondPanel.onchange=e=>{const order=e.target.dataset.productOrder;if(!order)return;rememberProduct();if(typeof bid==='string'){bond.order=order==='preserve'?'1':order;delete bond.query;}else{if(order==='preserve')delete productBondOverrides[bid];else productBondOverrides[bid]=order;delete productBondQueries[bid];}ed.render();};
  }
  editors.forEach(ed=>{
    const toolbar=node('<div class="ce-toolbar">'+icon('select','Selection mode','data-mode="selection"')+icon('edit','Edit atom / bond','data-mode="edit"')+'<span class="ce-divider"></span>'+icon('lasso','Lasso selection','data-shape="lasso"')+icon('box','Box selection','data-shape="box"')+'<span class="muted">Right-drag: pan · Wheel: zoom</span></div>');ed.canvas.before(toolbar);const help=node('<p class="ce-help">Click: toggle selection · Drag: lasso / box · Shift + click / drag: deselect</p>');toolbar.after(help);ed.help=help;ed.toolbar=toolbar;ed.counts=node('<div class="ce-counts">0 atoms · 0 bonds</div>');ed.canvas.after(ed.counts);
    const selected=node('<div class="ce-panel"><div class="section-title"><h3>Selected Items</h3>'+icon('clear','Clear selection')+'</div><div></div></div>');ed.selected=selected.lastElementChild;selected.querySelector('button').onclick=()=>{if(!ed.product)invalidateReactant();else rememberProduct();ed.atoms().clear();ed.bonds().clear();ed.render();};selected.onclick=e=>{if(ed.product&&(e.target.dataset.removeAtom!==undefined||e.target.dataset.removeBond!==undefined))rememberProduct();if(e.target.dataset.removeAtom!==undefined)deselectAtom(ed,Number(e.target.dataset.removeAtom));if(e.target.dataset.removeBond!==undefined)ed.bonds().delete(e.target.dataset.removeBond.startsWith('added:')?e.target.dataset.removeBond:Number(e.target.dataset.removeBond));if(e.target.dataset.removeAtom!==undefined||e.target.dataset.removeBond!==undefined){if(!ed.product)invalidateReactant();ed.render();}};ed.atomPanel=node('<div class="ce-panel"></div>');ed.bondPanel=node('<div class="ce-panel"></div>');if(!ed.product){ed.atomPanel.id='atomConstraints';ed.bondPanel.id='bondConstraints';}ed.right.prepend(selected,ed.atomPanel,ed.bondPanel);
    function paintToolbar(){ed.help.textContent=ed.tool==='add'?'Click two atoms to add a selected single bond.':ed.mode==='selection'?(ed.product?'Selected atoms / bonds form the product · Shift + click / drag: deselect':'Click: toggle selection · Drag: lasso / box · Shift + click / drag: deselect'):'Click a selected atom or bond to edit it. Selection stays unchanged.';toolbar.querySelectorAll('[data-mode]').forEach(b=>{b.classList.toggle('active',b.dataset.mode===ed.mode);b.setAttribute('aria-pressed',String(b.dataset.mode===ed.mode));});toolbar.querySelectorAll('[data-shape]').forEach(b=>{b.classList.toggle('active',b.dataset.shape===ed.shape);b.setAttribute('aria-pressed',String(b.dataset.shape===ed.shape));});}
    toolbar.onclick=e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.mode){ed.mode=b.dataset.mode;ed.tool=null;ed.step.querySelectorAll('[data-tool]').forEach(x=>x.classList.remove('active'));if(ed.product)productBondStart=null;}if(b.dataset.shape)ed.shape=b.dataset.shape;paintToolbar();inspector(ed);};paintToolbar();
    const zoom=node('<div class="ce-toolbar" style="justify-content:flex-end;margin-top:6px">'+icon('plus','Zoom in','data-zoom="0.8"')+icon('minus','Zoom out','data-zoom="1.25"')+icon('fit','Fit structure','data-zoom="fit"')+'</div>');ed.counts.after(zoom);
    function setView(){const svg=ed.canvas.querySelector('svg');if(svg)svg.setAttribute('viewBox',ed.view.join(' '));}
    function zoomAt(factor,q){const [x,y,w,h]=ed.view,nw=Math.max(100,Math.min(3500,w*factor)),nh=nw*440/700;ed.view=[q.x-(q.x-x)*nw/w,q.y-(q.y-y)*nh/h,nw,nh];setView();}
    zoom.onclick=e=>{const b=e.target.closest('[data-zoom]');if(!b)return;if(b.dataset.zoom==='fit')ed.view=fitView(ed);else zoomAt(Number(b.dataset.zoom),{x:ed.view[0]+ed.view[2]/2,y:ed.view[1]+ed.view[3]/2});setView();};
    let gesture;
    ed.canvas.oncontextmenu=e=>e.preventDefault();ed.canvas.onwheel=e=>{const svg=ed.canvas.querySelector('svg');if(!svg)return;e.preventDefault();gesture=null;const lasso=svg.querySelector('.selection-lasso');lasso.setAttribute('hidden','');lasso.style.display='none';zoomAt(e.deltaY>0?1.12:1/1.12,svgPoint(svg,e));};
    ed.canvas.onpointerdown=e=>{if(!ed.graph()||![0,2].includes(e.button))return;e.preventDefault();const svg=ed.canvas.querySelector('svg'),q=svgPoint(svg,e);gesture={pan:e.button===2,points:[q],start:q,target:e.target,remove:e.shiftKey,moved:false,view:[...ed.view]};svg.setPointerCapture(e.pointerId);};
    ed.canvas.onpointermove=e=>{if(!gesture)return;const svg=ed.canvas.querySelector('svg'),q=svgPoint(svg,e),g=gesture;if(g.pan){ed.view[0]-=q.x-g.start.x;ed.view[1]-=q.y-g.start.y;setView();return;}if(ed.mode!=='selection'||ed.tool){if(Math.hypot(q.x-g.start.x,q.y-g.start.y)>3)g.moved=true;return;}if(Math.hypot(q.x-g.start.x,q.y-g.start.y)<3&&!g.moved)return;g.moved=true;if(ed.shape==='box')g.points=[g.start,{x:q.x,y:g.start.y},q,{x:g.start.x,y:q.y},g.start];else g.points.push(q);const lasso=svg.querySelector('.selection-lasso');lasso.removeAttribute('hidden');lasso.style.display='block';lasso.setAttribute('points',g.points.map(p=>p.x+','+p.y).join(' '));};
    ed.canvas.onpointerup=()=>{if(!gesture)return;const g=gesture;gesture=null;if(g.pan)return;if(g.moved&&(ed.mode==='edit'||ed.tool))return;const atom=g.target.closest('[data-mol-atom]'),bond=g.target.closest(ed.product?'[data-product-bond]':'[data-mol-bond]'),a=atom?Number(atom.dataset.molAtom):null,token=bond?(ed.product?bond.dataset.productBond:bond.dataset.molBond):null,b=token===null?null:token.startsWith('added:')?token:Number(String(token).replace('base:',''));
      if(ed.product&&ed.tool){
        if(ed.tool==='add'&&a!==null){
          if(productDeletedAtoms.has(a))return;
          if(productBondStart===null){productBondStart=a;ed.render();return;}
          const begin=productBondStart;productBondStart=null;
          if(begin===a){ed.render();return;}
          const existing=productBondBetween(begin,a);
          if(existing){const id=existing.startsWith('base:')?Number(existing.slice(5)):existing;if(!productSelectedBonds.has(id)){rememberProduct();productSelectedBonds.add(id);}ed.render();return;}
          rememberProduct();const id=nextProductBondId++;productAddedBonds.push({id,begin,end:a,order:'1'});productSelectedBonds.add('added:'+id);ed.render();return;
        }

        ed.render();return;
      }
      if(ed.mode==='edit'){
        if(a!==null&&ed.atoms().has(a)){ed.focusAtom=a;ed.focusBond=null;if(ed.product){productSelectedAtom=a;productSelectedBond=null;}inspector(ed);}
        else if(b!==null&&ed.bonds().has(b)){ed.focusBond=b;ed.focusAtom=null;if(ed.product){productSelectedBond=token;productSelectedAtom=null;}inspector(ed);}
        return;
      }
      if(!ed.product)invalidateReactant();else rememberProduct();
      const mutate=(set,id)=>{if(g.remove||!g.moved&&ed.mode==='selection'&&set.has(id)){if(set===ed.atoms())deselectAtom(ed,id);else set.delete(id);}else set.add(id);};
      if(g.moved){const l=ed.layout(),graph=ed.graph();graph.atoms.forEach(a=>{if(pointInPolygon(l.x(a),l.y(a),g.points))mutate(ed.atoms(),a.index);});[...graph.bonds,...(ed.product?productAddedBonds.map(b=>({...b,index:'added:'+b.id})):[])].forEach(b=>{if(bondInsideLasso({x:l.x(graph.atoms[b.begin]),y:l.y(graph.atoms[b.begin])},{x:l.x(graph.atoms[b.end]),y:l.y(graph.atoms[b.end])},g.points))mutate(ed.bonds(),b.index);});}else{if(a!==null)mutate(ed.atoms(),a);if(b!==null)mutate(ed.bonds(),b);if(ed.product){productSelectedAtom=ed.mode==='edit'?a:null;productSelectedBond=ed.mode==='edit'?token:null;}}ed.render();
    };ed.canvas.onpointercancel=()=>{gesture=null;ed.render();};
    if(ed.product){const tools=node('<div class="ce-toolbar">'+icon('plus','Add single bond (edit its type in the inspector)','data-tool="add"')+icon('undo','Undo product edit','data-undo-product')+'</div>');toolbar.after(tools);ed.undo=tools.querySelector('[data-undo-product]');ed.undo.onclick=undoProduct;tools.onclick=e=>{const b=e.target.closest('[data-tool]');if(!b)return;ed.mode='edit';ed.tool=ed.tool===b.dataset.tool?null:b.dataset.tool;productBondStart=null;tools.querySelectorAll('[data-tool]').forEach(x=>x.classList.toggle('active',x.dataset.tool===ed.tool));paintToolbar();inspector(ed);};}

    ed.afterRender=()=>{setView();if(ed.undo)ed.undo.disabled=!productHistory.length;inspector(ed);if(ed.product){[...ed.bonds()].forEach(i=>{if(!getBond(ed,i)){ed.bonds().delete(i);delete productBondConstraints[i];}});ed.bonds().forEach(i=>ed.canvas.querySelector('[data-product-bond="'+(typeof i==='string'?i:'base:'+i)+'"]')?.classList.add('selected'));ed.canvas.querySelectorAll('[data-product-bond^="added:"]').forEach(x=>x.classList.add('ce-added'));}if(ed.product){stashProduct();paintProductList();}refreshOutputs();};
  });
  const baseRenderMolecule=renderMolecule;renderMolecule=()=>{baseRenderMolecule();editors[0].afterRender();};renderProduct=()=>{const canvas=el('productCanvas');if(!productGraph){canvas.replaceChildren();return;}const l=productLayout();canvas.innerHTML='<svg viewBox="0 0 700 440">'+productGraph.bonds.map(b=>productBondMarkup(b,l,'base:'+b.index,productBondOverrides[b.index]||'preserve')).join('')+productAddedBonds.map(b=>productBondMarkup({...b,index:b.id},l,'added:'+b.id,String(b.order))).join('')+productGraph.atoms.map(a=>productAtomMarkup(a,l)).join('')+'<polyline class="selection-lasso" hidden/></svg>';canvas.querySelectorAll('.bond-group').forEach(b=>b.classList.remove('selected'));editors[1].afterRender();};queryPanels=()=>{};
  el('clearSelection').onclick=()=>{const ed=body1.hidden?editors[1]:editors[0];if(!ed.product)invalidateReactant();else rememberProduct();ed.atoms().clear();ed.bonds().clear();ed.render();};
  resetVisualBuilder=()=>{activePattern=null;placeBuilder();++productLoadRevision;++generation;clearTimeout(timer);molGraph=null;selectedAtoms=new Set();selectedBonds=new Set();atomConstraintState={};bondConstraintState={};atomMapBySource={};visualPatternIndex=-1;visualProductIndex=-1;productGraph=null;productAtomMaps={};productAtomOverrides={};productBondOverrides={};productBondQueries={};productDeletedAtoms=new Set();productSelectedAtoms=new Set();productAddedBonds=[];nextProductBondId=1;productBondStart=null;productSelectedAtom=null;productSelectedBond=null;el('builderSmiles').value='';el('builderPatternName').value='';el('builderProductName').value='';el('moleculeCanvas').replaceChildren();el('productCanvas').replaceChildren();productList.replaceChildren();draftPattern=null;productStats.clear();productDrafts.clear();registerStatus.textContent='';body3.querySelector('.ce-error').textContent='';el('cleavagePatternSummary').textContent='';step3.querySelector('.ce-status').textContent='Waiting';el('builderSourceType').value='smiles';visualSourceType='smiles';productSelectedBonds.clear();productHistory=[];productConstraints={};productBondConstraints={};completed=false;reactantText='';productText='';summaryCopy.hidden=true;step1.querySelector('.ce-status').textContent='In progress';step1.querySelector('.ce-status').classList.remove('done');step2.querySelector('.ce-status').textContent='Waiting';editors.forEach(ed=>{ed.mode='selection';ed.shape='lasso';ed.tool=null;ed.focusAtom=null;ed.focusBond=null;ed.view=[0,0,700,440];ed.selected.innerHTML='';ed.atomPanel.innerHTML='<h3>Atom Constraints</h3>';ed.bondPanel.innerHTML='<h3>Bond Constraints</h3>';error(ed,'');ed.toolbar.querySelector('[data-mode="selection"]').click();ed.toolbar.querySelector('[data-shape="lasso"]').click();});productContainer.hidden=false;openStep(0);showOutputs();};
  async function generateReactant(){
    const r=await chemistry('reactant',{...sourcePayload(),name:el('builderPatternName').value,atoms:[...selectedAtoms],bonds:[...selectedBonds],constraints:atomConstraintState,bondConstraints:bondConstraintState,atomMapBySource});
    await chemistry('validate',{name:el('builderPatternName').value,reactant_smarts:r.smarts,products:[]});
    return r;
  }
  const generateButton=node('<button type="button" id="generateReactant" class="ce-apply">Generate SMARTS</button>');el('applyReactant').before(generateButton);
  generateButton.onclick=async()=>{clearTimeout(timer);const revision=++generation;generateButton.disabled=true;try{const r=await generateReactant();if(revision!==generation)return;reactantText=r.smarts;atomMapBySource=r.atomMapBySource;baseRenderMolecule();showOutputs();openStep(0);error(editors[0],'');}catch(e){if(revision===generation)error(editors[0],e.message);}finally{generateButton.disabled=false;}};
  // Apply confirms the reactant in the editor-local draft; registration is explicit.
  el('applyReactant').onclick=async()=>{try{clearTimeout(timer);++generation;el('applyReactant').disabled=true;const name=el('builderPatternName').value,r=await generateReactant();const next={name,reactant_smarts:r.smarts,products:JSON.parse(JSON.stringify(draftPattern?.products||[]))};await chemistry('validate',next);draftPattern=next;registerStatus.textContent='';atomMapBySource=r.atomMapBySource;baseRenderMolecule();reactantText=r.smarts;completed=true;summaryCopy.hidden=false;step1.querySelector('.ce-status').textContent='Completed';step1.querySelector('.ce-status').classList.add('done');step2.querySelector('.ce-status').textContent='Ready';await loadVisualProduct(-1);productContainer.hidden=false;openStep(1);showOutputs();error(editors[0],'');}catch(e){openStep(0);error(editors[0],e.message);}finally{el('applyReactant').disabled=false;}};
  // Keep the original input stable; changing constraints invalidates the completed snapshot.

  el('builderSmiles').addEventListener('input',()=>{invalidateReactant();++generation;clearTimeout(timer);});
  el('drawMolecule').onclick=async()=>{try{completed=false;openStep(0);editors[0].view=[0,0,700,440];visualSourceType=el('builderSourceType').value;molGraph=await chemistry('molecule',sourcePayload());selectedAtoms=new Set();selectedBonds=new Set();atomConstraintState={};bondConstraintState={};atomMapBySource={};editors[0].view=fitView(editors[0]);renderMolecule();error(editors[0],'');}catch(e){error(editors[0],e.message);}};
  loadVisualProduct=async index=>{
    stashProduct();const revision=++productLoadRevision;++generation;clearTimeout(timer);
    const pattern=draftPattern,product=index<0?null:pattern.products[index],reactant=pattern.reactant_smarts;
    // Resolve chemistry before changing the active Product or any shared editor state.
    const graph=await chemistry('molecule',{smarts:reactant});
    const state=product&&productDrafts.get(product)?.baseline!==null?await chemistry('productState',{reactantSmarts:reactant,productSmarts:product.smarts}):null;
    if(revision!==productLoadRevision||pattern!==draftPattern||product&&pattern.products[index]!==product)return;
    stashProduct();++generation;clearTimeout(timer);visualProductIndex=index;productGraph=graph;productAtomMaps=Object.fromEntries(graph.atoms.map(a=>[a.index,a.mapNumber||a.index+1]));productAtomOverrides={};productBondOverrides={};productBondQueries={};productAddedBonds=[];productConstraints={};productBondConstraints={};productDeletedAtoms=new Set();productHistory=[];productBondStart=null;productSelectedAtom=null;productSelectedBond=null;
    productSelectedAtoms=new Set(graph.atoms.map(a=>a.index));productSelectedBonds=new Set(graph.bonds.map(b=>b.index));
    if(state){productSelectedAtoms=new Set(state.keptAtoms);productSelectedBonds=new Set(state.keptBonds);productAtomOverrides=state.atomOverrides||{};productBondQueries=state.bondQueries||{};productBondOverrides=Object.fromEntries(Object.entries(state.bondOverrides||{}).filter(([,value])=>value!=='remove'));productAddedBonds=state.addedBonds||[];productAddedBonds.forEach(b=>productSelectedBonds.add('added:'+b.id));}
    nextProductBondId=Math.max(0,...productAddedBonds.map(b=>b.id))+1;productText=product?product.smarts:reactant;el('builderProductName').value=product?product.name:'';editors[1].focusAtom=null;editors[1].focusBond=null;editors[1].view=fitView(editors[1]);
    if(product){const draft=productDrafts.get(product);if(draft?.state){restoreProductSnapshot(draft.state);el('builderProductName').value=draft.name;productText=draft.text;productHistory=draft.history||[];}else if(!draft){productDrafts.set(product,{baseline:productFingerprint(),savedState:productSnapshot(),savedName:product.name,savedText:product.smarts});}}
    renderProduct();renderProductChoices();showOutputs();
  };
  renderProductChoices=()=>{el('applyProduct').textContent='Save';paintProductList();};
  async function hydrateProductStats(){const pattern=draftPattern;if(!pattern)return;await Promise.all(pattern.products.map(async product=>{if(productStats.has(product.smarts))return;try{const graph=await chemistry('molecule',{smarts:product.smarts});productStats.set(product.smarts,graphStats(graph));}catch(e){error(editors[1],e.message);}}));if(draftPattern===pattern)paintProductList();}
  function paintProductList(){productList.replaceChildren();(draftPattern?.products||[]).forEach((product,index)=>{
    const draft=productDrafts.get(product),name=draft?.name||product.name||'Product '+(index+1);
    const card=node('<div class="ce-product-item"><button type="button" data-visual-product="'+index+'">'+htmlEscape(name)+(draft?.dirty?' *':'')+'</button>'+icon('clear','Remove product '+(index+1),'data-remove-product-draft="'+index+'"')+'</div>');
    const b=card.querySelector('[data-visual-product]');b.classList.toggle('active',index===visualProductIndex);b.setAttribute('aria-pressed',String(index===visualProductIndex));b.onclick=busyAction(b,async()=>{try{await loadVisualProduct(index);}catch(e){error(editors[1],e.message);}},false);
    card.querySelector('[data-remove-product-draft]').onclick=()=>removeProduct(index);productList.append(card);
  });productList.append(addProductButton);el('applyProduct').disabled=visualProductIndex<0;productDrawing.hidden=visualProductIndex<0;right2.hidden=visualProductIndex<0;el('builderProductName').closest('label').hidden=visualProductIndex<0;productActions.hidden=visualProductIndex<0;restoreSavedButton.hidden=visualProductIndex<0;const activeDraft=productDrafts.get(draftPattern?.products[visualProductIndex]);restoreSavedButton.disabled=!activeDraft?.savedState||!activeDraft.dirty;}
  async function removeProduct(index){try{stashProduct();const active=visualProductIndex,product=draftPattern.products[index];productDrafts.delete(product);draftPattern.products.splice(index,1);visualProductIndex=-1;if(active===index){await loadVisualProduct(draftPattern.products.length?Math.min(index,draftPattern.products.length-1):-1);}else{visualProductIndex=active>index?active-1:active;paintProductList();}registerStatus.textContent='';error(editors[1],'');}catch(e){error(editors[1],e.message);}}
  addProductButton.title='Add product';addProductButton.setAttribute('aria-label','Add product');addProductButton.onclick=async()=>{if(!completed){error(editors[1],'Apply the reactant first.');return;}try{stashProduct();const product={name:'product_'+(draftPattern.products.length+1),smarts:draftPattern.reactant_smarts};draftPattern.products.push(product);productDrafts.set(product,{baseline:null,dirty:true});await loadVisualProduct(draftPattern.products.length-1);registerStatus.textContent='';}catch(e){error(editors[1],e.message);}};
  editVisualPattern=async index=>{resetVisualBuilder();visualPatternIndex=index;activePattern=cleavageModel.cleavage_pattern_set.patterns[index];placeBuilder();draftPattern=JSON.parse(JSON.stringify(cleavageModel.cleavage_pattern_set.patterns[index]));visualSourceType='smarts';el('builderSourceType').value='smarts';el('visualBuilder').hidden=false;jumpToCleavage(root);el('builderSmiles').value=draftPattern.reactant_smarts;el('builderPatternName').value=draftPattern.name;try{molGraph=await chemistry('molecule',{smarts:draftPattern.reactant_smarts});selectedAtoms=new Set(molGraph.atoms.map(a=>a.index));selectedBonds=new Set(molGraph.bonds.map(b=>b.index));molGraph.atoms.forEach(a=>{atomConstraintState[a.index]=defaultAtom(a);atomMapBySource[a.index]=a.mapNumber||a.index+1;});reactantText=draftPattern.reactant_smarts;completed=true;renderMolecule();summaryCopy.hidden=false;step1.querySelector('.ce-status').textContent='Completed';step1.querySelector('.ce-status').classList.add('done');step2.querySelector('.ce-status').textContent='Ready';await loadVisualProduct(draftPattern.products.length?0:-1);openStep(1);await hydrateProductStats();}catch(e){error(editors[0],e.message);}};
  async function commitProduct(){try{if(!completed||!productGraph||visualProductIndex<0)throw new Error('Select a product to save.');clearTimeout(timer);const revision=++generation,pattern=draftPattern,index=visualProductIndex,previous=pattern.products[index],name=el('builderProductName').value.trim()||'product_'+(index+1),payload=productPayload();const r=await chemistry('productFromSelection',payload);if(revision!==generation||pattern!==draftPattern||visualProductIndex!==index||pattern.products[index]!==previous)return false;const products=pattern.products.slice(),next={name,smarts:r.smarts};products[index]=next;await chemistry('validate',{...pattern,products});if(revision!==generation||pattern!==draftPattern||visualProductIndex!==index||pattern.products[index]!==previous)return false;pattern.products=products;productDrafts.delete(previous);el('builderProductName').value=next.name;productDrafts.set(next,{baseline:productFingerprint(),savedState:productSnapshot(),savedName:next.name,savedText:r.smarts});productStats.set(r.smarts,selectionStats(editors[1]));productText=r.smarts;stashProduct();registerStatus.textContent='';renderProductChoices();showOutputs();error(editors[1],'');return true;}catch(e){error(editors[1],e.message);return false;}}
  const registerStatus=node('<p role="status" class="ce-help"></p>'),registerButton=node('<button type="button" class="ce-apply" id="registerCleavagePattern">Register Pattern</button>');body3.append(registerButton);root.after(registerStatus);registerButton.textContent='Add Cleavage Pattern to Set';const nextStepButton=node('<button type="button" class="ce-apply" id="reviewCleavagePattern">Continue to Step 3 →</button>');body2.append(nextStepButton);nextStepButton.onclick=()=>openStep(2);
  registerButton.onclick=async()=>{try{if(!completed||!draftPattern){openStep(0);throw new Error('Apply the reactant first.');}if(!draftPattern.products.length){openStep(1);throw new Error('Add at least one product before registering the pattern.');}stashProduct();const dirty=draftPattern.products.findIndex(product=>productDrafts.get(product)?.dirty);if(dirty>=0){await loadVisualProduct(dirty);openStep(1);throw new Error('Save modified products before registering the pattern.');}registerButton.disabled=true;const next={...draftPattern,name:el('builderPatternName').value.trim()};await chemistry('validate',next);const value=JSON.parse(JSON.stringify(next));if(visualPatternIndex<0){visualPatternIndex=cleavageModel.cleavage_pattern_set.patterns.length;cleavageModel.cleavage_pattern_set.patterns.push(value);}else cleavageModel.cleavage_pattern_set.patterns[visualPatternIndex]=value;draftPattern=next;activePattern=value;renderCleavage();registerStatus.textContent='Cleavage Pattern added to Pattern Set.';step3.querySelector('.ce-status').textContent='Added';body3.querySelector('.ce-error').textContent='';root.hidden=true;jumpToPattern(visualPatternIndex);}catch(e){body3.querySelector('.ce-error').textContent=e.message;[body1,body2,body3].find(body=>!body.hidden).querySelector('.ce-error').textContent=e.message;}finally{registerButton.disabled=false;}};
  const generateProductButton=node('<button type="button" class="ce-apply" id="generateProduct">Generate SMARTS</button>');const productActions=node('<div class="ce-product-actions"></div>');el('applyProduct').before(productActions);el('applyProduct').classList.add('ce-apply');productActions.append(generateProductButton,el('applyProduct'));
  const restoreSavedButton=node('<button type="button" id="restoreSavedProduct" title="Discard edits and restore the last saved Product">Restore Saved</button>');productActions.after(restoreSavedButton);
  restoreSavedButton.onclick=()=>{const product=draftPattern?.products[visualProductIndex],draft=productDrafts.get(product);if(!draft?.savedState)return;++productLoadRevision;++generation;clearTimeout(timer);restoreProductSnapshot(draft.savedState);el('builderProductName').value=draft.savedName;productText=draft.savedText;productHistory=[];productBondStart=null;editors[1].focusAtom=null;editors[1].focusBond=null;registerStatus.textContent='';renderProduct();showOutputs();error(editors[1],'');};
  generateProductButton.onclick=async()=>{clearTimeout(timer);const revision=++generation;generateProductButton.disabled=true;try{const r=await chemistry('productFromSelection',productPayload());await chemistry('validate',{name:el('builderPatternName').value,reactant_smarts:reactantText,products:[{name:el('builderProductName').value||'product',smarts:r.smarts}]});if(revision!==generation)return;productText=r.smarts;showOutputs();error(editors[1],'');}catch(e){if(revision===generation)error(editors[1],e.message);}finally{generateProductButton.disabled=false;}};
  el('applyProduct').textContent='Save';el('applyProduct').onclick=()=>commitProduct();
  productAtomMarkup=(a,l)=>'<g data-mol-atom="'+a.index+'" class="mol-atom '+(productBondStart===a.index||productSelectedAtoms.has(a.index)?'selected ':'')+(productDeletedAtoms.has(a.index)?'deleted':'')+'" transform="translate('+l.x(a)+' '+l.y(a)+')"><circle class="atom-hit" r="25"/><circle class="atom-label-bg" r="17"/><text class="atom-symbol" style="fill:'+atomColor(a.symbol)+'" text-anchor="middle" dominant-baseline="central">'+htmlEscape(productAtomMaps[a.index])+'</text></g>';

  root.querySelectorAll(':scope > .actions').forEach(n=>{if(!n.children.length)n.remove();});
  root.querySelectorAll(':scope > label').forEach(n=>{if(!n.querySelector('input,select'))n.remove();});
  [el('drawMolecule'),el('generateReactant'),el('applyReactant'),addProductButton,generateProductButton,el('applyProduct'),registerButton].forEach(button=>{button.onclick=busyAction(button,button.onclick);});
  el('addVisualPattern').onclick=()=>{resetVisualBuilder();root.hidden=false;jumpToCleavage(root,el('builderSmiles'));};
  el('closeBuilder').onclick=()=>{const index=visualPatternIndex;root.hidden=true;resetVisualBuilder();if(index>=0)jumpToPattern(index);else jumpToCleavage(el('addVisualPattern'),el('addVisualPattern'));};
  resetVisualBuilder();
}
exports.script=()=>`(${installCleavageEditor.toString()})(${JSON.stringify(require('./periodic-table').rows)});`;
