from __future__ import annotations

from dataclasses import dataclass
from typing import Dict, List, Optional, Tuple

import numpy as np
import pandas as pd

from ...libs.msentity.msentity import MSDataset
from ...libs.msentity.msentity.core.PeakSeries import PeakSeries


@dataclass
class GeneratedSpectrumPeak:
    """One formula-grouped generated peak."""

    mz: float
    intensity: float
    sample_id: int
    formula: Optional[str] = None


@dataclass
class GeneratedMassSpectrum:
    """Generated mass spectrum for one sample."""

    sample_id: int
    peaks: List[GeneratedSpectrumPeak]


@dataclass
class FragmentSpectrumGeneratorOutput:
    """Output of SourceAnchoredFragmentSpectrumGenerator prediction, as spectra."""

    spectra: List[GeneratedMassSpectrum]


def fragment_spectrum_output_to_msdataset(output: FragmentSpectrumGeneratorOutput, *, metadata: Optional[pd.DataFrame] = None) -> MSDataset:
    spectra = output.spectra
    if metadata is None:
        metadata = pd.DataFrame({"sample_id": [s.sample_id for s in spectra]})
    else:
        metadata = metadata.reset_index(drop=True).copy()
    if len(metadata) != len(spectra):
        raise ValueError("metadata rows must match generated spectra count.")
    peak_rows: List[Tuple[float, float]] = []
    peak_metadata_rows: List[Dict[str, object]] = []
    offsets = [0]
    for spectrum in spectra:
        for peak in spectrum.peaks:
            peak_rows.append((float(peak.mz), float(peak.intensity)))
            peak_metadata_rows.append({"sample_id": int(peak.sample_id), "formula": peak.formula})
        offsets.append(len(peak_rows))
    data = np.asarray(peak_rows, dtype=np.float64)
    if data.size == 0:
        data = np.empty((0, 2), dtype=np.float64)
    peak_series = PeakSeries(data=data, offsets=np.asarray(offsets, dtype=np.int64), metadata=pd.DataFrame(peak_metadata_rows), metadata_columns=["sample_id", "formula"], sort_by_mz=True)
    return MSDataset(spectrum_metadata=metadata, peak_series=peak_series, columns=metadata.columns.tolist(), description="In silico spectra generated by CLEFTS")


def create_spectrum_generator(params: Dict):
    from .source_anchored_spectrum_predictor import SourceAnchoredFragmentSpectrumGenerator
    config = dict(params)
    # Training initialization metadata is not a generator constructor argument.
    config.pop("mol_encoder_checkpoint", None)
    architecture = config.pop("architecture", None)
    if architecture not in (None, SourceAnchoredFragmentSpectrumGenerator.architecture):
        raise ValueError(f"Unknown spectrum generator architecture: {architecture}")
    return SourceAnchoredFragmentSpectrumGenerator(**config)
