from __future__ import annotations

from dataclasses import dataclass
from typing import Any, List, Tuple, Dict, Optional

from bidict import bidict
from rdkit import Chem
from rdkit.Chem import rdChemReactions

from clefts.libs.mmkit.mmkit import Compound


@dataclass(frozen=True)
class ProductMolecule:
    """One product molecule generated by a cleavage event."""

    id: int
    compound: Compound
    product_indices: Tuple[int, ...]

@dataclass(frozen=True)
class CleavageProduct:
    """One cleavage event generated by one ProductRule."""

    id: int
    rule_name: str
    reactant_indices: Tuple[int, ...]
    product_molecules: Tuple[ProductMolecule, ...]

@dataclass(frozen=True)
class _CleavageResult:
    """Result of applying one CleavagePattern to one reactant molecule."""

    cleavage: _CleavagePattern
    reactant_compound: Compound
    products: Tuple[CleavageProduct, ...]

    def __init_subclass__(cls, **kwargs):
        super().__init_subclass__(**kwargs)

        if "copy" not in cls.__dict__:
            raise TypeError(
                f"{cls.__name__} must override copy()."
            )


@dataclass(frozen=True)
class ProductRule:
    """One product-side template.

    `smarts` is equivalent to the right-hand side of a SMIRKS rule.
    It can contain one product or multiple products separated by ".".
    """

    name: str
    smarts: str

    def __repr__(self) -> str:
        return f"ProductRule(name={self.name}, smarts={self.smarts})"

    def __str__(self) -> str:
        return f"(name={self.name}, smarts={self.smarts})"

@dataclass(frozen=True)
class CleavageReaction:

    id: int
    source_rule: ProductRule

    smirks: str
    rxn: rdChemReactions.ChemicalReaction
    react_temp: Any
    prod_temp: rdChemReactions.MOL_SPTR_VECT

    react_idx_to_map: bidict[int, int]
    prod_idx_to_maps: Tuple[bidict[int, int], ...]

    virtual_smirks: str
    virtual_rxn: rdChemReactions.ChemicalReaction

@dataclass(frozen=True)
class _CleavagePattern:

    name: str
    reactant_smarts: str
    reactant_query: Chem.Mol
    cleavage_reactions: Tuple[CleavageReaction, ...]

    def __init_subclass__(cls, **kwargs):
        super().__init_subclass__(**kwargs)

        if "copy" not in cls.__dict__:
            raise TypeError(
                f"{cls.__name__} must override copy()."
            )
        
    @classmethod
    def from_rules(
        cls,
        reactant_smarts: str,
        products: Tuple[ProductRule, ...],
        name: str = "",
    ) -> _CleavagePattern:
        """Create a CleavagePattern from SMARTS and ProductRule objects.

        This method performs the heavy validation/compilation that was
        previously done in `__init__`.
        """

        reactant_query = Chem.MolFromSmarts(reactant_smarts)
        if reactant_query is None:
            raise ValueError(f"Invalid reactant SMARTS: {reactant_smarts}")

        unique_product_by_smarts: Dict[str, ProductRule] = {}

        for product in products:
            if product.smarts not in unique_product_by_smarts:
                unique_product_by_smarts[product.smarts] = product

        unique_products = tuple(
            unique_product_by_smarts[smarts]
            for smarts in sorted(unique_product_by_smarts)
        )        

        cleavage_reactions: List[CleavageReaction] = []

        for product_index, product in enumerate(unique_products):
            smirks = f"{reactant_smarts}>>{product.smarts}"

            rxn = rdChemReactions.ReactionFromSmarts(smirks)
            if rxn is None:
                raise ValueError(f"Invalid SMIRKS for product: {smirks}")

            if len(rxn.GetReactants()) != 1:
                raise ValueError(
                    "Only single-reactant patterns are supported: "
                    f"{smirks}"
                )

            react_temp = rxn.GetReactants()[0]
            prod_temps = rxn.GetProducts()

            react_map_nums = cls._extract_unique_atom_maps(
                mol=react_temp,
                smarts=reactant_smarts,
                side_name="reactant",
            )

            react_idx_to_map = bidict(
                {idx: atom_map for idx, atom_map in enumerate(react_map_nums)}
            )

            existing_product_map_nums: set[int] = set()
            prod_idx_to_map_list: List[bidict[int, int]] = []

            for prod_temp in prod_temps:
                product_map_nums = cls._extract_unique_atom_maps(
                    mol=prod_temp,
                    smarts=product.smarts,
                    side_name="product",
                )

                existing_product_map_nums.update(product_map_nums)

                prod_idx_to_map_list.append(
                    bidict(
                        {
                            idx: atom_map
                            for idx, atom_map in enumerate(product_map_nums)
                        }
                    )
                )

            virtual_smirks = cls._build_virtual_smirks(
                reactant_smarts=reactant_smarts,
                product_smarts=product.smarts,
                react_map_nums=tuple(react_map_nums),
                product_map_nums=tuple(existing_product_map_nums),
            )

            virtual_rxn = rdChemReactions.ReactionFromSmarts(virtual_smirks)
            if virtual_rxn is None:
                raise ValueError(
                    f"Invalid virtual SMIRKS for product: {virtual_smirks}"
                )

            cleavage_reactions.append(
                CleavageReaction(
                    id=product_index,
                    source_rule=product,
                    smirks=smirks,
                    rxn=rxn,
                    react_temp=react_temp,
                    prod_temp=prod_temps,
                    react_idx_to_map=react_idx_to_map,
                    prod_idx_to_maps=tuple(prod_idx_to_map_list),
                    virtual_smirks=virtual_smirks,
                    virtual_rxn=virtual_rxn,
                )
            )

        return cls(
            name=name,
            reactant_smarts=reactant_smarts,
            reactant_query=reactant_query,
            cleavage_reactions=tuple(cleavage_reactions),
        )

    @staticmethod
    def _extract_unique_atom_maps(
        mol: Chem.Mol,
        smarts: str,
        side_name: str,
    ) -> Tuple[int, ...]:
        """Extract atom-map numbers and validate that they are unique."""

        atom_maps: List[int] = []

        for atom in mol.GetAtoms():
            atom_map = atom.GetAtomMapNum()

            if atom_map <= 0:
                raise ValueError(
                    f"All atoms in {side_name} SMARTS must have atom maps: "
                    f"{smarts}"
                )

            if atom_map in atom_maps:
                raise ValueError(
                    f"Duplicate atom map numbers in {side_name} SMARTS: "
                    f"{smarts}"
                )

            atom_maps.append(atom_map)

        return tuple(atom_maps)

    @staticmethod
    def _build_virtual_smirks(
        reactant_smarts: str,
        product_smarts: str,
        react_map_nums: Tuple[int, ...],
        product_map_nums: Tuple[int, ...],
    ) -> str:
        """Add dummy products for reactant atoms absent from the product side.

        This makes RDKit preserve mapping information for atoms that disappear
        from the actual product template.
        """

        missing_maps = sorted(set(react_map_nums) - set(product_map_nums))

        if not missing_maps:
            return f"{reactant_smarts}>>{product_smarts}"

        dummy_products = ".".join(f"[*:{atom_map}]" for atom_map in missing_maps)

        return f"{reactant_smarts}>>{product_smarts}.{dummy_products}"

    def __repr__(self) -> str:
        return (
            "CleavagePattern("
            f"name={self.name}, "
            f"reactant_smarts={self.reactant_smarts}, "
            f"products={'.'.join(str(product) for product in self.products)}"
            ")"
        )

    def __eq__(self, other: object) -> bool:
        if not isinstance(other, _CleavagePattern):
            return False
        return self.key == other.key

    def __hash__(self) -> int:
        return hash(self.key)

    @property
    def products(self) -> Tuple[ProductRule, ...]:
        return tuple(
            cleavage_reaction.source_rule
            for cleavage_reaction in self.cleavage_reactions
        )

    def exists(self, compound: Compound) -> bool:
        return compound.mol.HasSubstructMatch(self.reactant_query)

    def matches(self, compound: Compound) -> List[Tuple[int, ...]]:
        return list(compound.mol.GetSubstructMatches(self.reactant_query))
    
    def fragment(self, compound: Compound) -> Optional[_CleavageResult]:

        if not self.exists(compound):
            return None

        mol = Chem.Mol(compound._mol)

        # Mapping: original atom-map number -> atom index in canonical Compound
        old_atom_map_to_idx = compound.atom_map_to_index

        # Mapping: RDKit atom index <-> atom-map number in the copied molecule
        idx_to_atom_map = bidict(
            {
                atom.GetIdx(): atom.GetAtomMapNum()
                for atom in mol.GetAtoms()
                if atom.GetAtomMapNum() > 0
            }
        )

        cleavage_products: List[CleavageProduct] = []

        for cleavage_reaction in self.cleavage_reactions:
            product_rule = cleavage_reaction.source_rule
            virtual_rxn = cleavage_reaction.virtual_rxn

            real_product_count = len(cleavage_reaction.prod_idx_to_maps)

            product_sets = virtual_rxn.RunReactants((mol,))

            for product_group in product_sets:
                # product_group contains:
                #   [real product 1, real product 2, ..., dummy product 1, ...]
                real_product_mols = product_group[:real_product_count]

                atom_mapping_cache: Dict[int, Dict[str, int]] = {}

                # -------------------------------------------------------------
                # 1. Collect atom mapping information from all real and dummy products
                # -------------------------------------------------------------
                for product_mol_index, product_mol in enumerate(product_group):
                    for atom in product_mol.GetAtoms():
                        if not (
                            atom.HasProp("react_atom_idx")
                            and atom.HasProp("old_mapno")
                        ):
                            continue

                        parent_idx = int(atom.GetProp("react_atom_idx"))
                        old_mapno = int(atom.GetProp("old_mapno"))

                        if parent_idx not in idx_to_atom_map:
                            continue

                        if old_mapno not in cleavage_reaction.react_idx_to_map.inverse:
                            continue

                        atom_map = idx_to_atom_map[parent_idx]
                        react_idx = cleavage_reaction.react_idx_to_map.inverse[old_mapno]

                        old_idx_in_canonical = old_atom_map_to_idx[atom_map]

                        product_mol_no = -1
                        product_idx = -1

                        # Find which real product template contains this atom map.
                        for real_idx, prod_idx_to_map in enumerate(
                            cleavage_reaction.prod_idx_to_maps
                        ):
                            if old_mapno in prod_idx_to_map.inverse:
                                product_mol_no = real_idx
                                product_idx = prod_idx_to_map.inverse[old_mapno]
                                break

                        atom_mapping_cache[atom_map] = {
                            "react_idx": react_idx,
                            "product_mol_no": product_mol_no,
                            "product_idx": product_idx,
                            "old_idx": old_idx_in_canonical,
                        }

                        # Restore original atom-map number to generated product atom.
                        atom.SetAtomMapNum(atom_map)

                # -------------------------------------------------------------
                # 2. Convert real product molecules to Compound objects
                # -------------------------------------------------------------
                new_compounds: List[Compound] = []

                try:
                    for real_product_mol in real_product_mols:
                        new_compounds.append(Compound(real_product_mol))
                except Exception:
                    continue

                # -------------------------------------------------------------
                # 3. Build reactant indices and product indices
                # -------------------------------------------------------------
                reactant_indices = [-1] * len(cleavage_reaction.react_idx_to_map)

                product_indices_list: List[List[int]] = [
                    [-1] * len(prod_idx_to_map)
                    for prod_idx_to_map in cleavage_reaction.prod_idx_to_maps
                ]

                new_atom_map_to_idx_list = [
                    new_compound.atom_map_to_index
                    for new_compound in new_compounds
                ]

                for atom_map, info in atom_mapping_cache.items():
                    reactant_indices[info["react_idx"]] = info["old_idx"]

                    product_mol_no = info["product_mol_no"]
                    product_idx = info["product_idx"]

                    if product_mol_no == -1 or product_idx == -1:
                        continue

                    new_atom_map_to_idx = new_atom_map_to_idx_list[product_mol_no]

                    if atom_map not in new_atom_map_to_idx:
                        continue

                    product_indices_list[product_mol_no][product_idx] = (
                        new_atom_map_to_idx[atom_map]
                    )

                # -------------------------------------------------------------
                # 4. Consistency check
                # -------------------------------------------------------------
                if not all(idx != -1 for idx in reactant_indices):
                    continue

                if not all(
                    idx != -1
                    for product_indices in product_indices_list
                    for idx in product_indices
                ):
                    continue

                # -------------------------------------------------------------
                # 5. Store result
                # -------------------------------------------------------------
                cleaved_molecules = tuple(
                    ProductMolecule(
                        id=idx,
                        compound=new_compound,
                        product_indices=tuple(product_indices),
                    )
                    for idx, (new_compound, product_indices) in enumerate(zip(
                        new_compounds,
                        product_indices_list,
                    ))
                )

                cleavage_products.append(
                    CleavageProduct(
                        id=cleavage_reaction.id,
                        rule_name=product_rule.name,
                        reactant_indices=tuple(reactant_indices),
                        product_molecules=cleaved_molecules,
                    )
                )

        return _CleavageResult(
            cleavage=self,
            reactant_compound=compound,
            products=tuple(cleavage_products),
        )
    
    @property
    def key(self) -> str:
        """Return a readable semantic key of this cleavage pattern.

        The name is intentionally excluded because it is metadata.
        """
        product_smarts_key = "|".join(
            product.smarts
            for product in self.products
        )

        return f"{self.reactant_smarts}>>{product_smarts_key}"

    def copy(self) -> _CleavagePattern:
        """Return a copy of this cleavage pattern."""
        return _CleavagePattern.from_rules(
            reactant_smarts=self.reactant_smarts,
            products=tuple(
                ProductRule(
                    name=cleavage_reaction.source_rule.name,
                    smarts=cleavage_reaction.source_rule.smarts,
                )
                for cleavage_reaction in self.cleavage_reactions
            ),
            name=self.name,
        )

if __name__ == "__main__":
    reactant_smarts = "[#8:1]=[#6:2]1:[#6:3]:[#6:4](-[#6:5]2:[#6:6]:[#6:7]:[#6:8](-[#8:9]):[#6:10]:[#6:11]:2):[#8:12]:[#6:13]2:[#6:14]:[#6:15](-[#8:16]):[#6:17]:[#6:18](-[#8:19]):[#6:20]:1:2"
    a_side_product_smarts  = "[#8:12]-[#6:13]1:[#6:14]:[#6:15](-[#8:16]):[#6:17]:[#6:18](-[#8:19]):[#6:20]:1"
    b_side_product_smarts = "[#8:1]=[#6:2]-[#6:3]=[#6:4](-[#6:5]1:[#6:6]:[#6:7]:[#6:8](-[#8:9]):[#6:10]:[#6:11]:1)"
    
    product_rules = (
        ProductRule(name="1,3", smarts="[#8:12]-[#6:13]1:[#6:14]:[#6:15](-[#8:16]):[#6:17]:[#6:18](-[#8-:19]):[#6:20]:1.[#8:1]=[#6:2]-[#6:3]=[#6:4](-[#6:5]1:[#6:6]:[#6:7]:[#6:8](-[#8:9]):[#6:10]:[#6:11]:1)"),

        ProductRule(name="1,4", smarts="[#6:20]1:[#6:13]:[#6:14]:[#6:15](-[#8:16]):[#6:17]:[#6:18](-[#8-:19]):1.[#6:4](-[#6:5]1:[#6:6]:[#6:7]:[#6:8](-[#8:9]):[#6:10]:[#6:11]:1)=[#8:12]"),

        ProductRule(name="1,2", smarts="[#6:4](-[#6:5]1:[#6:6]:[#6:7]:[#6:8](-[#8-:9]):[#6:10]:[#6:11]:1)=[#6:3]"),

        ProductRule(name="0,4", smarts="[#6:5]1:[#6:6]:[#6:7]:[#6:8](-[#8-:9]):[#6:10]:[#6:11]:1"),
    )
    cleavage_pattern = _CleavagePattern.from_rules(
        reactant_smarts=reactant_smarts,
        products=product_rules,
        name="Example Cleavage",
    )

    compound = Compound.from_smiles("O=c1cc(-c2ccc(O)c(CCC)c2)oc2cc(O)cc(O)c12")
    result = cleavage_pattern.fragment(compound)
    
    if result is not None and result.products:
        print(f"Cleavage successful for {compound.smiles}:")

        for product_index, product in enumerate(result.products, start=1):
            print(f"  Product {product_index}:")
            print(f"    Rule name: {product.rule_name}")
            print(f"    Reactant indices: {product.reactant_indices}")

            for molecule_index, molecule in enumerate(product.product_molecules, start=1):
                print(f"    Product molecule {molecule_index}:")
                print(f"      Product SMILES: {molecule.smiles}")
                print(f"      Product indices: {molecule.product_indices}")

    else:
        print(f"No cleavage match for {compound.smiles}.")