from __future__ import annotations
from typing import Tuple, TYPE_CHECKING
if TYPE_CHECKING:
    from .CleavagePattern import CleavagePattern
    from .CleavageProduct import CleavageProduct

class CleavageResult:
    """Result of applying one cleavage pattern to one molecule.

    ``CleavageResult`` is a lightweight container returned by
    :meth:`CleavagePattern.fragment`. It keeps the pattern that was applied, the
    canonical SMILES of the reactant molecule, and all products accepted by the
    pattern's charge filter.

    The object is immutable by convention: values are stored internally and
    exposed through read-only properties.
    """

    def __init__(
        self,
        cleavage: CleavagePattern,
        reactant_smiles: str,
        products: Tuple['CleavageProduct', ...],
    ):
        """Create a cleavage result.

        Parameters
        ----------
        cleavage : CleavagePattern
            Cleavage pattern that generated this result.
        reactant_smiles : str
            Canonical SMILES of the molecule before cleavage.
        products : tuple of CleavageProduct
            Products generated by this cleavage pattern.
        """
        self._cleavage = cleavage
        self._reactant_smiles = reactant_smiles
        self._products = tuple(products)

    @property
    def cleavage(self) -> CleavagePattern:
        """Cleavage pattern that produced this result."""
        return self._cleavage

    @property
    def reactant_smiles(self) -> str:
        """Canonical SMILES of the molecule before cleavage."""
        return self._reactant_smiles

    @property
    def products(self) -> Tuple['CleavageProduct', ...]:
        """Products generated by the cleavage pattern."""
        return self._products

    def __repr__(self) -> str:
        return (
            f"CleavageResult("
            f"cleavage='{self._cleavage}', "
            f"reactant='{self._reactant_smiles}', "
            f"n_products={len(self._products)})"
        )

