from __future__ import annotations
from typing import Tuple

class CleavageProduct:
    """Single molecular product generated by a cleavage pattern.

    ``CleavageProduct`` stores the product SMILES and the atom-index mapping
    needed to trace the product back to the matched atoms in the original
    molecule. The mapping is expressed with two aligned tuples:
    ``reactant_indices`` for atom indices in the reactant and
    ``product_indices`` for the corresponding atom indices in the product.
    """

    def __init__(
        self,
        smiles: str,
        reactant_indices: Tuple[int, ...],
        product_indices: Tuple[int, ...],
    ):
        """Create a cleavage product.

        Parameters
        ----------
        smiles : str
            Canonical SMILES of the generated product molecule.
        reactant_indices : tuple of int
            Atom indices in the original reactant molecule. The order follows
            the mapped atoms on the reactant side of the cleavage pattern.
        product_indices : tuple of int
            Atom indices in the generated product molecule. The order follows
            the mapped atoms on the product side of the cleavage pattern.
        """
        self._smiles = smiles
        self._reactant_indices = tuple(reactant_indices)
        self._product_indices = tuple(product_indices)

    @property
    def smiles(self) -> str:
        """Canonical SMILES of this generated product."""
        return self._smiles

    @property
    def reactant_indices(self) -> Tuple[int, ...]:
        """Atom indices in the original reactant molecule."""
        return self._reactant_indices

    @property
    def product_indices(self) -> Tuple[int, ...]:
        """Atom indices in the generated product molecule."""
        return self._product_indices

    def __repr__(self) -> str:
        return (
            f"CleavageProduct("
            f"smiles='{self._smiles}', "
            f"reactant_indices={self._reactant_indices}, "
            f"product_indices={self._product_indices})"
        )