const vscode=require('vscode');
const fs=require('fs');
const path=require('path');
const ui=require('./ui');
const {commonCss,formCss}=require('../cleavage-pattern-set/styles');
const pathDrop=require('../../webview-path-drop');
const host=require('../cleavage-pattern-set/host');
const VIEW_TYPE='clefts.adductRuleSetEditor',RULE_VIEW_TYPE='clefts.adductRuleEditor',FILE_SUFFIX='.adductset.json',RULE_SUFFIX='.adduct.json';
function normalizeRule(value){if(!value||typeof value!=='object'||Array.isArray(value)||'fragment_ion_adduct_rule_set'in value)throw new Error('The JSON must contain one fragment ion adduct rule.');const unsaturation=Number(value.unsaturation??0);if(!Number.isFinite(unsaturation))throw new Error('Adduct rule unsaturation must be a finite number.');return {name:String(value.name||''),adduct_type:String(value.adduct_type||''),radical:!!value.radical,unsaturation,ion_shifts:Array.isArray(value.ion_shifts)?value.ion_shifts.map(shift=>{const result={ion_shift:String(shift?.ion_shift||'')};if(Array.isArray(shift?.atoms))result.atoms=shift.atoms.map(String);return result;}):[]};}
function normalizeDocument(value){if(!value||typeof value!=='object'||Array.isArray(value))throw new Error('The JSON root must be an object.');const set=value.fragment_ion_adduct_rule_set;if(!set||typeof set!=='object'||Array.isArray(set))throw new Error('The JSON must contain a fragment_ion_adduct_rule_set object.');return {fragment_ion_adduct_rule_set:{name:String(set.name||''),adduct_rules:Array.isArray(set.adduct_rules)?set.adduct_rules.map(normalizeRule):[]}};}
class Provider{
 constructor(context,singleRule=false){this.context=context;this.singleRule=singleRule;}
 resolveCustomTextEditor(document,panel){const context=this.context,singleRule=this.singleRule;panel.webview.options={enableScripts:true};panel.webview.html=editorHtml(singleRule);let applying=false;
  const current=()=>{const source=JSON.parse(document.getText());return singleRule?{fragment_ion_adduct_rule_set:{name:'',adduct_rules:[normalizeRule(source)]}}:normalizeDocument(source);};
  const send=()=>{try{panel.webview.postMessage({type:'adductRuleSet',value:current(),path:document.uri.fsPath});}catch(error){panel.webview.postMessage({type:'adductRuleError',message:error.message});}};
  const subscription=vscode.workspace.onDidChangeTextDocument(event=>{if(event.document.uri.toString()===document.uri.toString()&&!applying)send();});panel.onDidDispose(()=>subscription.dispose());
  const write=async raw=>{const value=normalizeDocument(raw);if(singleRule&&value.fragment_ion_adduct_rule_set.adduct_rules.length!==1)throw new Error('An adduct rule file must contain exactly one rule.');const saved=singleRule?value.fragment_ion_adduct_rule_set.adduct_rules[0]:value,text=JSON.stringify(saved,null,2)+'\n';if(text===document.getText())return;const edit=new vscode.WorkspaceEdit();edit.replace(document.uri,new vscode.Range(document.positionAt(0),document.positionAt(document.getText().length)),text);applying=true;const ok=await vscode.workspace.applyEdit(edit);applying=false;if(!ok)throw new Error('The document could not be updated.');};
  panel.webview.onDidReceiveMessage(async message=>{try{if(message.type==='ready'){send();return;}if(message.type==='update'){await write(message.value);return;}if(message.type==='selectElements'){const elements=await host.showElementPicker(message.elements);if(elements)panel.webview.postMessage({type:'elementSelectionResult',requestId:message.requestId,elements});return;}if(message.type==='loadAdductRuleSet'||message.type==='loadAdductRule'){const source=await host.readCleavageImport(context,message);if(!source)return;if(message.type==='loadAdductRuleSet')panel.webview.postMessage({type:'adductRuleSet',value:normalizeDocument(source.value),path:source.path});else panel.webview.postMessage({type:'adductRuleLoaded',rule:normalizeRule(source.value),index:message.index,path:source.path});return;}if(message.type==='saveAdductRuleSet'){const value=normalizeDocument(message.value),selected=await vscode.window.showSaveDialog({filters:{'CLEFTS Fragment Ion Adduct Rule Set':['json']},defaultUri:vscode.Uri.file(host.cleavagePatternSetSavePath(value.fragment_ion_adduct_rule_set.name,message.path,FILE_SUFFIX))});if(selected){const target=vscode.Uri.file(host.ensureFileSuffix(selected.fsPath,FILE_SUFFIX));await fs.promises.writeFile(target.fsPath,JSON.stringify(value,null,2)+'\n');panel.webview.postMessage({type:'adductRuleSetSaved',path:target.fsPath});vscode.window.showInformationMessage(`Saved ${path.basename(target.fsPath)}`);}return;}if(message.type==='saveAdductRule'){const rule=normalizeRule(message.rule),selected=await vscode.window.showSaveDialog({filters:{'CLEFTS Fragment Ion Adduct Rule':['json']},defaultUri:vscode.Uri.file(host.safeFileStem(rule.name||'adduct_rule')+RULE_SUFFIX)});if(selected){const target=vscode.Uri.file(host.ensureFileSuffix(selected.fsPath,RULE_SUFFIX));await fs.promises.writeFile(target.fsPath,JSON.stringify(rule,null,2)+'\n');vscode.window.showInformationMessage(`Saved ${path.basename(target.fsPath)}`);}return;}}catch(error){panel.webview.postMessage({type:'adductRuleError',message:String(error.message||error)});}});
 }
}
function register(context){for(const [type,single]of[[VIEW_TYPE,false],[RULE_VIEW_TYPE,true]])context.subscriptions.push(vscode.window.registerCustomEditorProvider(type,new Provider(context,single),{webviewOptions:{retainContextWhenHidden:true},supportsMultipleEditorsPerDocument:false}));}
function editorHtml(singleRule=false){return `<!doctype html><html><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><style>${commonCss()}${formCss()}${pathDrop.css()}</style></head><body><main>${ui.html(singleRule)}<script>const vscode=acquireVsCodeApi();${ui.state()}${ui.script(singleRule)}${pathDrop.script()}document.getElementById('adductApp').hidden=false;let syncTimer;onAdductChange=()=>{clearTimeout(syncTimer);syncTimer=setTimeout(()=>vscode.postMessage({type:'update',value:adductModel}),200);};vscode.postMessage({type:'ready'});</script></main></body></html>`;}
module.exports={register,normalizeRule,normalizeDocument,editorHtml,FILE_SUFFIX,RULE_SUFFIX,VIEW_TYPE,RULE_VIEW_TYPE};
