/* Shared Fragment Ion Adduct Rule Set and single-rule editing surface. */
function html(singleRule=false){return `<div id="adductApp" data-app-panel="adduct" hidden><p id="adductError" class="danger" role="alert"></p><section><div class="section-title"><div><h2>${singleRule?'Fragment Ion Adduct Rule':'Fragment Ion Adduct Rule Set'}</h2><p id="adductPath" class="muted">Not saved</p></div><div class="actions"><button type="button" id="applyParameterAdductRules" hidden>Apply Adduct Rules to Parameters</button><button type="button" id="loadAdductSet" class="file-drop-zone" ${singleRule?'hidden':''}>Drop an adduct rule set here or click to Browse</button><button type="button" id="saveAdductSet" ${singleRule?'hidden':''}>Save Configuration</button></div></div><label ${singleRule?'hidden':''}>Rule set name<input id="adductSetName" placeholder="default_fragment_ion_adduct_rule_set"></label></section><section ${singleRule?'hidden':''}><h2>Create or Import an Adduct Rule</h2><p class="muted">Rules define the precursor adduct, radical and unsaturation limits, and permitted fragment-ion composition shifts.</p><div class="actions"><button type="button" id="addAdductRule" class="primary">Add Adduct Rule</button><button type="button" id="loadSingleAdductRule" class="file-drop-zone">Drop an adduct rule here or click to Browse</button></div><p id="adductEmpty" class="muted">No adduct rules yet. Add a rule or load a rule set to begin.</p></section><div id="adductRules"></div></div>`;}
function state(){return `let adductPath='',adductModel={fragment_ion_adduct_rule_set:{name:'',adduct_rules:[]}},onAdductChange=()=>{};`;}
function client(singleRule=false){
  const el=id=>document.getElementById(id),clone=value=>JSON.parse(JSON.stringify(value));
  const newRule=()=>({name:'',adduct_type:'[M+H]+',radical:false,unsaturation:0,ion_shifts:[]});
  const newShift=()=>({ion_shift:'[M+H]+'});
  let elementRequest=0,elementTarget=null;
  function node(tag,text){const value=document.createElement(tag);if(text!==undefined)value.textContent=text;return value;}
  function button(text,action){const value=node('button',text);value.type='button';value.onclick=action;return value;}
  function label(text,input){const value=node('label',text);value.append(input);return value;}
  function input(type,value,change){const control=node('input');control.type=type;if(type==='checkbox')control.checked=!!value;else control.value=value??'';control.oninput=()=>change(type==='checkbox'?control.checked:type==='number'?Number(control.value):control.value);return control;}
  function changed(){onAdductChange();}
  function reopen(ri,si){const rule=el('adductRules').querySelectorAll('.adduct-rule-card')[ri];if(!rule)return;rule.open=true;if(si!==undefined){const shift=rule.querySelectorAll('.ion-shift-card')[si];if(shift)shift.open=true;}}
  function render(){
    const set=adductModel.fragment_ion_adduct_rule_set,rules=set.adduct_rules||[];el('adductSetName').value=set.name||'';el('adductEmpty').hidden=rules.length>0;const host=el('adductRules');host.replaceChildren();
    rules.forEach((rule,ri)=>{
      const card=node('details');card.className='adduct-rule-card';const summary=node('summary',(rule.name||('Adduct Rule '+(ri+1)))+' · '+(rule.adduct_type||'No adduct'));card.append(summary);
      const actions=node('div');actions.className='actions';actions.append(button('Load',()=>vscode.postMessage({type:'loadAdductRule',index:ri})),button('Save',()=>vscode.postMessage({type:'saveAdductRule',rule:clone(rule)})));if(!singleRule)actions.append(button('Remove Rule',()=>{rules.splice(ri,1);render();changed();}));card.append(actions);
      const grid=node('div');grid.className='grid';grid.append(label('Rule name',input('text',rule.name,value=>{rule.name=value;summary.textContent=(value||('Adduct Rule '+(ri+1)))+' · '+(rule.adduct_type||'No adduct');changed();})),label('Adduct type',input('text',rule.adduct_type,value=>{rule.adduct_type=value;summary.textContent=(rule.name||('Adduct Rule '+(ri+1)))+' · '+(value||'No adduct');changed();})),label('Maximum unsaturation',input('number',rule.unsaturation,value=>{rule.unsaturation=value;changed();})));
      const radical=input('checkbox',rule.radical,value=>{rule.radical=value;changed();});const radicalLabel=label('Radical',radical);radicalLabel.className='check';grid.append(radicalLabel);card.append(grid);
      const shiftsTitle=node('div');shiftsTitle.className='section-title product-title';shiftsTitle.append(node('h3','Ion Shifts'),button('Add Ion Shift',()=>{(rule.ion_shifts||(rule.ion_shifts=[])).push(newShift());render();const latest=host.querySelectorAll('.adduct-rule-card')[ri];latest.open=true;latest.querySelectorAll('.ion-shift-card')[rule.ion_shifts.length-1].open=true;changed();}));card.append(shiftsTitle);
      const shifts=node('div');shifts.className='ion-shift-list';(rule.ion_shifts||[]).forEach((shift,si)=>{
        const item=node('details');item.className='ion-shift-card',itemSummary=node('summary',(shift.ion_shift||'Ion shift')+(shift.atoms?.length?' · '+shift.atoms.join(', '):' · all elements'));item.append(itemSummary);
        item.append(label('Ion shift',input('text',shift.ion_shift,value=>{shift.ion_shift=value;itemSummary.textContent=(value||'Ion shift')+(shift.atoms?.length?' · '+shift.atoms.join(', '):' · all elements');changed();})));
        const restricted=input('checkbox',Array.isArray(shift.atoms),value=>{if(value)shift.atoms=[];else delete shift.atoms;render();reopen(ri,si);changed();});const restrictedLabel=label('Restrict elements',restricted);restrictedLabel.className='check';item.append(restrictedLabel);
        if(Array.isArray(shift.atoms)){const atoms=input('text',shift.atoms.join(', '),value=>{shift.atoms=value.split(',').map(v=>v.trim()).filter(Boolean);changed();});item.append(label('Elements (comma separated)',atoms),button('Select Elements',()=>{elementTarget={ri,si};vscode.postMessage({type:'selectElements',requestId:'adduct-'+(++elementRequest),elements:shift.atoms});}));}
        item.append(button('Remove Ion Shift',()=>{rule.ion_shifts.splice(si,1);render();changed();}));shifts.append(item);
      });card.append(shifts);host.append(card);
    });
  }
  el('adductSetName').oninput=event=>{adductModel.fragment_ion_adduct_rule_set.name=event.target.value;changed();};
  el('addAdductRule').onclick=()=>{adductModel.fragment_ion_adduct_rule_set.adduct_rules.push(newRule());render();const card=el('adductRules').lastElementChild;if(card){card.open=true;card.scrollIntoView({block:'start'});}changed();};
  el('loadAdductSet').onclick=()=>vscode.postMessage({type:'loadAdductRuleSet'});el('saveAdductSet').onclick=()=>vscode.postMessage({type:'saveAdductRuleSet',value:adductModel,path:adductPath});el('loadSingleAdductRule').onclick=()=>vscode.postMessage({type:'loadAdductRule',index:-1});
  for(const [id,type]of [['loadAdductSet','loadAdductRuleSet'],['loadSingleAdductRule','loadAdductRule']]){const zone=el(id);zone.ondragover=event=>{event.preventDefault();zone.classList.add('path-drop-active');};zone.ondragleave=()=>zone.classList.remove('path-drop-active');zone.ondrop=async event=>{event.preventDefault();event.stopPropagation();zone.classList.remove('path-drop-active');try{const path=pathFromDataTransfer(event.dataTransfer);if(path)vscode.postMessage({type,path,index:-1});else if(event.dataTransfer.files?.[0])vscode.postMessage({type,json:await event.dataTransfer.files[0].text(),index:-1});else throw new Error('Drop an adduct JSON file.');}catch(error){el('adductError').textContent=error.message;}};}
  window.addEventListener('message',event=>{const message=event.data;if(message.type==='adductRuleError')el('adductError').textContent=message.message;if(['adductRuleSet','adductRuleLoaded','adductRuleSetSaved'].includes(message.type))el('adductError').textContent='';if(message.type==='adductRuleSet'){adductModel=message.value;adductPath=message.path||'';el('adductPath').textContent=adductPath||'Not saved';render();changed();}if(message.type==='adductRuleSetSaved'){adductPath=message.path;el('adductPath').textContent=adductPath;}if(message.type==='adductRuleLoaded'){const rules=adductModel.fragment_ion_adduct_rule_set.adduct_rules;if(message.index>=0)rules[message.index]=message.rule;else rules.push(message.rule);render();changed();}if(message.type==='elementSelectionResult'&&String(message.requestId).startsWith('adduct-')&&elementTarget){const {ri,si}=elementTarget;adductModel.fragment_ion_adduct_rule_set.adduct_rules[ri].ion_shifts[si].atoms=message.elements;elementTarget=null;render();reopen(ri,si);changed();}});
  window.renderAdductRules=render;render();
}
function script(singleRule=false){return `(${client.toString()})(${JSON.stringify(singleRule)});`;}
module.exports={html,state,script};
